package org.opencb.cellbase.core.variant.annotation.hgvs;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mortbay.util.ajax.JSON;
import org.opencb.biodata.models.core.Gene;
import org.opencb.biodata.models.core.Transcript;
import org.opencb.biodata.models.variant.Variant;
import org.opencb.commons.utils.FileUtils;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by fjlopez on 14/02/17.
 */
public class HgvsProteinCalculatorTest {

    private ObjectMapper jsonObjectMapper;
    List<Gene> geneList;

    public HgvsProteinCalculatorTest() throws IOException {

    }

    @Before
    public void setUp() throws IOException {

        jsonObjectMapper = new ObjectMapper();
        jsonObjectMapper.configure(MapperFeature.REQUIRE_SETTERS_FOR_GETTERS, true);
        jsonObjectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

        geneList = loadGenes(Paths.get(getClass().getResource("/hgvs/gene.test.json.gz").getFile()));
    }

    @Test
    public void testInsert() throws Exception {
        // 17:18173905:-:A  indel   ENSP00000408800 p.Leu757AlafsTer79      p.Leu757fs      fs_shorthand_same_pos
        Gene gene = getGene("ENSG00000091536");
        Transcript transcript = getTranscript(gene, "ENST00000418233");
        Variant variant = new Variant("17",
                18173905,
                "-",
                "A");

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);

        String expected =
                "TCATCCTAGGAGGTGCCTGTGGCCGGGCGCAGTAGCTCATGCCTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGCGGACCACCTGAGGTCAGGAATTTGAGACTAGCCGGCCCAACATGGCGAAACCCCATCTCTACTAAACATACAAAAAATTAGCCAGGCGTCGTGGCGGGCGCCTGTAATCCCAGCTACTCAGGAGGCTGAGGCAGGAGAATCGCTTGAACCCAGGAGGCGGAGCTTGCAGTGGGCCGAGATTGCGCCACTGCACTCTAGCCTGGGGGACAACAGCGAAACTCCGTCTCAAAAATATATATATATATTAATTAAATAAAAAAACGAGGTGCCTTCTCCTGACTCCCTGATCCCCGCGCTCTCCAGCTCTGCCCTCGCGATCGCTGGAGCCCCCTGAGGAACTCACGCAGACGCGGCTGCACCGCCTCATCAATCCCAACTTCTACGGCTATCAGGACGCCCCCTGGAAGATCTTCCTGCGCAAAGAGGTGTTTTACCCCAAGGACAGCTACAGCCATCCTGTGCAGCTTGACCTCCTGTTCCGGCAGATCCTGCACGACACGCTCTCCGAGGCCTGCCTTCGCATCTCTGAGGATGAGAGGCTCAGGAATGAAGGCCTTGTTTGCCCAGAACCAGCTGGACACACAGAAGCCTCTGGTAACGGAAAGCGTGAAGCGGGCCGTGGTCAGCACTGCACGAGACACCTGGGAGGTCTACTTCTCCCGCATCTTCCCCGCCACGGGCAGCGTGGGCACTGGTGTGCAGCTCCTAGCTGTGTCCCACGTGGGCATCAAACTCCTGAGGATGGTCAAGGGTGGCCAGGAGGCCGGCGGGCAGCTGCGGGTCCTGCGTGCATACAGCTTTGCAGATATCCTGTTTGTGACCATGCCCTCCCAGAACATGCTGGAGTTCAACCTGGCCAGTGAGAAGGTCATCCTCTTCTCAGCCCGAGCGCACCAGGTCAAGACCCTGGTAGATGACTTCATCTTGGAGCTGAAGAAGGACTCTGACTACGTGGTCGCTGTGAGGAACTTCCTGCCTGAGGACCCTGCGCTGCTGGCTTTCCACAAGGGTGACATCATACACCTGCAGCCCCTAGAGCCACCTCGAGTGGGCTACAGTGCTGGCTGCGTGGTTCGCAGGAAGGTGGTGTACCTGGAGGAGCTGCGACGTAGAGGCCCCGACTTTGGCTGGAGGTTCGGGACCATCCACGGGCGCGTGGGCCGCTTCCCTTCGGAGCTGGTGCAGCCCGCTGCTGCCCCCGACTTCCTGCAGCTGCCAACGGAGCCAGGCCGCGGCCGAGCAGCCGCCGTGGCCGCTGCTGTGGCCTCTGCAGCCGCTGCACAGGAGGTGGGCCGCAGGAGAGAGGGTCCCCCAGTCAGGGCCCGCTCTGCTGACCATGGGGAGGACGCCCTGGCGCTCCCACCCTACACAATGCTCGAGTTTGCCCAGAAGTATTTCCGAGACCCTCAGAGGAGACCCCAGGATGGCCTCAGGCTGAAATCCAAGGAGCCTCGGGAGTCCAGAACCTTGGAGGACATGCTTTGCTTCACCAAGACTCCCCTCCAGGAATCCCTCATCGAACTCAGCGACAGCAGCCTCAGCAAGATGGCCACCGACATGTTCCTAGCTGTAATGAGGTTCATGGGGGATGCCCCACTGAAGGGCCAGAGTGACCTGGACGTGCTTTGTAACCTCCTGAAGCTGTGCGGGGACCATGAGGTCATGCGGGATGAATGTTACTGCCAAGTTGTGAAGCAGATCACAGACAATACCAGCTCCAAGCAGGACAGCTGCCAGCGAGGCTGGAGGCTGCTGTATATCGTGACCGCCTACCACAGCTGCTCTGAGGTCCTCCACCCACACCTCACTCGCTTCCTCCAAGACGTGAGCCGGACCCCAGGCCTGCCCTTTCAGGGGATCGCCAAGGCCTGCGAGCAGAACCTGCAGAAAACCTTGCGCTTCGGAGGTCGTCTGGAGCTCCCCAGCAGCATAGAGCTTCGGGCCATGTTGGCAGGCCGCAGTTCCAAGAGGCAACTCTTTCTTCTTCCTGGAGGCCTTGAACGCCATCTCAAAATCAAAACATGCACTGTGGCCCTGGACGTGGTGGAAGAGATATGTGCTGAGATGGCTCTGACACGCCCTGAGGCCTTCAATGAATATGTTATCTTCGTTGTCACCAACCGTGGCCAGCATGTGTGCCCACTCAGTCGCCGTGCTTACATCCTGGATGTGGCCTCAGAGATGGAGCAGGTGGACGGCGGCTACATGCTCTGGTTCCGGCGTGTGCTCTGGGATCAGCCACTCAAGTTCGAGAATGAGCTATATGTGACCATGCACTACAACCAGGTCCTGCCTGACTACCTGAAGGGACTCTTCAGCAGTGTGCCGGCCAGCCGGCCCAGCGAGCAGCTGCTGCAGCAGGTGTCCAAGCTGGCTTCACTGCAGCATCGCGCCAAGGACCACTTCTACCTGCCGAGCGTGCGGGAAGTCCAGGAGTACATCCCAGCCCAGCTCTACCGTACAACGGCAGGCTCGACCTGGCTCAACCTGGTCAGCCAGCACCGGCAGCAGACACAGGCGCTCAGCCCCCACCAGGCCCGTGCCCAGTTTCTGGGCCTCCTCAGCGCCTTACCTATGTTCGGCTCCTCCTTCTTCTTCATCCAGAGCTGCAGCAACATTGCTGTGCCAGCCCCTTGCATCCTTGCCATCAACCACAATGGCCTCAACTTTCTCAGCACAGAGACTCATGAATTGATGGTGAAGTTCCCCCTGAAGGAGATCCAGTCGACGCGGACCCAGCGGCCCACGGCCAACTCCAGCTACCCCTATGTGGAGATTGCGCTGGGGGACGTGGCGGCCCAGCGCACCTTGCAGCTGCAGCTGGAGCAGGTAAGAGCTGGGGAAGTGTTGGATGGGCGTGGACTGTCACTGTCACCTGCAGGGACTGGAACTGTGTCGTGTGGTGGCCGTGCACGTGGAGAACCTGCTCAGTGCCCATGAGAAGCGGCTCACATTGCCCCCCAGCGAGATCACCCTGCTCTGACCCAGCCCCCAGCCCTCCAGTACCTTCTGCCAGAAGACTCACTGTGTGGCCTCAGAGAAATCACTGAACCTCTCAGGATCAATGACCCCTGTAAGGGGCCAGAGCCTTGGAGGACACTAAGAGGAGGCAGGAGGAGCAACTCAAATCCCCAAGAACACAAGAAGACCCATCCTGAACTGGGATGGAATGGCAGCATGCAAACTTGGATCAGATAGCAGGAGGAACTTTCAAAAGTCTGGCCCACTGTGCAGTGGAGCAGAAGGCAGGACCATGAGGCCTCCTGCCATGTACCCATTGCAGACCCTGCCCCTAACTCCTGCCTATGACACAGAAGCCCCACACCAGTTGCCCA";

        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void testDeletion() throws Exception {
        // 2:47822224:T:-  2       47822224        T       -       indel   ENSP00000385398 p.Ile482PhefsTer6       p.Ile482fs
        Gene gene = getGene("ENSG00000138081");
        Transcript transcript = getTranscript(gene, "ENST00000402508");
        Variant variant = new Variant("2",
                47822224,
                "T",
                "-");

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);

        String expected =
                "ATCATAGCAATAAGATTTGTAAAACATTGCAATGGCTGAAAAACTGTCTAACAGGAAATTTTAAGTGTTATTCCAAAGAAGAACAAGCCTAAAAATGATGATGTGCCTGCAGATTGGTTGCAGAAGAATCAGGTCCTGGTGCACAAAATAGTCCATACCAACTTCGTAGAAAAACTCTTTTGCCGAAAAGAACAGCGTGTCCCACAAAGAACAGTATGGAGGGCGCCTCAACTTCAACTACAGAAAACTTTGGTCATCGTGCAAAACGTGCAAGAGTGTCTGGAAAATCACAAGATCTATCAGCAGCACCTGCTGAACAGTATCTTCAGGAGAAACTGCCAGATGAAGTGGTTCTAAAAATCTTCTCTTACTTGCTGGAACAGGATCTTTGTAGAGCAGCTTGTGTATGTAAACGCTTCAGTGAACTTGCTAATGATCCAATTTTGTGGAAACGATTATATATGGAAGTATTTGAATATACTCGCCCTATGATGCATCCTGAACCTGGAAAATTCTACCAGATTAATCCAGAAGAGTATGAACATCCAAATCCCTGGAAAGAGAGTTTCCAGCAGTTGTATAAAGGTGCACATGTAAAGCCAGGATTTGCTGAACATTTCTACAGTAACCCTGCAAGATATAAAGGAAGAGAAAATATGTTGTATTATGATACTATTGAAGATGCCCTTGGTGGGGTACAAGAGGCTCATTTTGATGGACTTATCTTTGTTCATTCTGGAATATATACTGATGAATGGATATATATTGAATCTCCAATCACCATGATTGGTGCAGCACCTGGGAAAGTGGCAGACAAAGTTATAATTGAAAACACTAGAGATTCAACCTTCGTTTTTATGGAAGGCTCTGAAGATGCTTATGTTGGATATATGACAATAAGGTTTAACCCTGATGACAAATCTGCACAACACCACAATGCACACCACTGCTTAGAGATTACAGTAAATTGTAGCCCTATTATTGATCACTGTATCATCCGAAGTACATGTACAGTTGGTTCTGCAGTATGTGTTAGTGGTCAAGGAGCATGTCCCACCATCAAGCACTGTAACATCAGTGACTGTGAAAATGTTGGACTATATATAACAGATCATGCACAGGGAATATATGAGGATAATGAAATTTCCAATAATGCGTTAGCTGGGATTTGGGTTAAAAATCATGGAAACCCAATTATTAGACGGAATCATATTCATCATGGACGTGATGTTGGTGTGTTCACATTTGATCATGGCATGGGTTACTTTGAAAGTTGCAATATACACAGAAATAGGATAGCAGGCTTTGAAGTAAAAGCCTATGCTAACCCTACAGTGGTTCGATGTGAAATTCACCATGGGCAGACTGGAGGAATATATGTCCATGAAAAAGGAAGAGGACAATTCATAGAGAATAAAATCTATGCAAACAACTTTGCAGGTGTATGGATTACCTCAAATAGTGACCCAACAATAAGGGGAAATTCTATATTTAATGGAAATCAAGGAGGAGTTTACATCTTTGGTGATGGACGAGGCCTTATTGAAGGAAATGACATTTATGGCAATGCATTAGCAGGAATTCAAATTAGGACAAACAGTTGTCCAATTGTTCGGCATAACAAAATTCATGATGGCCAGCATGGTGGGATTTATGTGCATGAAAAGGGACAAGGAGTAATAGAAGAGAATGAAGTTTATAGTAACACTCTAGCTGGAGTCTGGGTGACAACTGGCAGCACTCCAGTACTGAGAAGAAACCGGATACACAGTGGCAAGCAGGTTGGTGTTTATTTTTATGACAATGGACATGGAGTGCTAGAAGACAATGATATCTATAATCATATGTATTCAGGGGTTCAGATAAGGACTGGAAGCAACCCCAAAATTAGACGCAACAAAATCTGGGGAGGACAGAATGGTGGAATTCTAGTTTATAATTCTGGTCTAGGCTGTATAGAAGACAATGAAATATTTGACAATGCAATGGCTGGAGTCTGGATTAAGACAGATAGTAATCCTACACTAAGAAGAAATAAAATCCATGATGGAAGAGATGGTGGCATCTGTATATTTAATGGGGGTCGAGGTCTCCTTGAAGAAAATGATATTTTCAGGAATGCTCAAGCAGGTGTTCTCATCAGCACTAATAGTCATCCAATCTTAAGGAAAAACAGAATATTTGATGGATTTGCCGCAGGTATTGAAATTACAAATCACGCAACTGCAACACTAGAAGGCAATCAGATTTTTAACAACCGGTTTGGAGGCTTATTTTTAGCATCTGGTGTTAATGTGACAATGAAAGATAACAAAATAATGAACAATCAAGATGCCATAGAAAAGGCTGTTAGTAGAGGCCAATGTTTATATAAAATATCAAGTTATACCAGCTATCCCATGCATGATTTCTACAGATGTCATACTTGTAACACCACAGATCGAAATGCCATATGTGTGAACTGCATTAAGAAGTGCCATCAGGGACATGATGTAGAGTTTATTAGACATGATAGGTTTTTCTGTGACTGTGGTGCTGGAACACTGTCTAATCCTTGTACATTAGCTGGTGAGCCTACACATGATACAGATACACTATATGACTCTGCTCCACCTATAGAATCTAATACATTGCAGCACAACTGAATTCCTTCCCTAAAGAAAAAGTCCTGCCATTGTAACATCATAACTTAAAACACTTTTTTGGAAGAAGATTTAAAATATTTGCCCATGCTACAGGAAGAGACTGTATTAAAAATGGATACACAAGGTCAGTTGACACTATGAAGCTCAAGCTACCAAAAAGAAAGTGGCAATATATTGACTCAGGATCTCAAAGCTGGGTGTTTTAGCATTACTGTGTAAAGACTTGAAGGGACAGAAGTGAAGAAAATAAGCTGCAATTTTGTACAGATACCAACTTCTGAAAAGCTGGTGTTTTTACAACTAGCATTGAATGCAGTCCAATTTGCAGTAGTAATCTTCAATAGACAAGCAGCTTTGTTGCTGCCTTTATGGACATGGGTACCAATTGCTTTTGTAATATGGTAAAAATGTGAGCTAGCACTTCTGCGTTCCTTTTGATTTTTTTTTTTTAACATGTATTCAGATTGAGAAATATGATTTTAATGCTTTAATCTCATGTAGTTTGTTTTTAATTTCAAGCAAAATCTTACTGTACTTGAATGTGCCCTGTTTTGTTAGCACACCTAGACTTGCTGTAACTGTACTCATGTCCCAGTATGTACGTTCTTTCTATGAAAGAGAAAACACTAATCTTAAATTATATCCAGCAATGTTTCTGGTATCCTTTAAGAAAAGTTAAGACTATTATTTCCTTCCCTTCCCTGTGCAGCATTCAAAATCACCCCTAGAAAAAGTGAGTGTTTTAATGAGACTTCCTAGGAAGGGATGCACTGTAAAACAAAAGTATTCTTGTAACTCAGTTTTGTGAAAGGTAAAAAACTACTATGTTTTAAGTACACTTTAGAAAGTCTCTTCAAAACAAACAGTCCTGTATTTGAACTCTGTTCATAGTTTTTTTTTGAACAGTTTAGACAAAACTGCTGGAAATTAAACCAATTTCCTGCATTAAGCTGAGACAAGTATATATACAGCCCTATACAGTTTCATAGCTTTTCCTCCCCCATTTATGTGTATTGGTGACAGTGGGTATAAAACAGCCTGAAAGTGTATGCATGTACCATAACATCTAGACTTAATATATTGTGGAGTATTCAATAACCATTATGTAGAAGGTAGATAAGAATTAAAAGGGTTTAATTTCCTAGAAAGAAAATGGAAAAATGGTCATTTTTAAAAAATAAAGTTTATTAGATCATAA";

        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void testSNV() throws Exception {
//        59      3:155143536:G:A 3       155143536       G       A       snv     ENSP00000417079 p.Val428Met             cb_empty
//        60      3:155143536:G:A 3       155143536       G       A       snv     ENSP00000418525 p.Val428Met             cb_empty
//        61      3:155143536:G:A 3       155143536       G       A       snv     ENSP00000420389 p.Val428Met             cb_empty
//        62      3:155143536:G:A 3       155143536       G       A       snv     ENSP00000419653 p.Val428Met             cb_empty
//        63      3:155143536:G:A 3       155143536       G       A       snv     ENSP00000353679 p.Val428Met             cb_empty
//        64      3:155143536:G:A 3       155143536       G       A       snv     ENSP00000478173 p.Val428Met             cb_empty
//        66      19:11131339:C:A 19      11131339        C       A       snv     ENSP00000453557 p.Leu890Met             cb_empty
        Gene gene = getGene("ENSG00000196549");
        Transcript transcript = getTranscript(gene, "ENST00000492661");
        Variant variant = new Variant("3",
                155143536,
                "G",
                "A");

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);

        String expected =
                "ACATTCCTACTGAGTATGACGAATGGTTGTTGATGGTTATCACTGGAGATTGAAAACTGGGATTCCTTTTTCACCAGGAATTGGTGCCTACCATGGCTGGGGATACACAGTGATGGATTTG"
                        + "TGACTTGCTCCTCTGAAAGCTGGCCCAAGGGTGTACAGCATATGAATGTGGGGGAGTTTACACTACACACGCTCTTGGCTATTTTAGGTGATGGGCAAGTCAGAAAGTCAG"
                        + "ATGGATATAACTGATATCAACACTCCAAAGCCAAAGAAGAAACAGCGATGGACTCCACTGGAGATCAGCCTCTCGGTCCTTGTCCTGCTCCTCACCATCATAGCTGTGACA"
                        + "ATGATCGCACTCTATGCAACCTACGATGATGGTATTTGCAAGTCATCAGACTGCATAAAATCAGCTGCTCGACTGATCCAAAACATGGATGCCACCACTGAGCCTTGTACA"
                        + "GACTTTTTCAAATATGCTTGCGGAGGCTGGTTGAAACGTAATGTCATTCCCGAGACCAGCTCCCGTTACGGCAACTTTGACATTTTAAGAGATGAACTAGAAGTCGTTTTG"
                        + "AAAGATGTCCTTCAAGAACCCAAAACTGAAGATATAGTAGCAGTGCAGAAAGCAAAAGCATTGTACAGGTCTTGTATAAATGAATCTGCTATTGATAGCAGAGGTGGAGAA"
                        + "CCTCTACTCAAACTGTTACCAGACATATATGGGTGGCCAGTAGCAACAGAAAACTGGGAGCAAAAATATGGTGCTTCTTGGACAGCTGAAAAAGCTATTGCACAACTGAAT"
                        + "TCTAAATATGGGAAAAAAGTCCTTATTAATTTGTTTGTTGGCACTGATGATAAGAATTCTGTGAATCATGTAATTCATATTGACCAACCTCGACTTGGCCTCCCTTCTAGA"
                        + "GATTACTATGAATGCACTGGAATCTATAAAGAGGCTTGTACAGCATATGTGGATTTTATGATTTCTGTGGCCAGATTGATTCGTCAGGAAGAAAGATTGCCCATCGATGAA"
                        + "AACCAGCTTGCTTTGGAAATGAATAAAGTTATGGAATTGGAAAAAGAAATTGCCAATGCTACGGCTAAACCTGAAGATCGAAATGATCCAATGCTTCTGTATAACAAGATG"
                        + "ACATTGGCCCAGATCCAAAATAACTTTTCACTAGAGATCAATGGGAAGCCATTCAGCTGGTTGAATTTCACAAATGAAATCATGTCAACTGTGAATATTAGTATTACAAAT"
                        + "GAGGAAGATGTGGTTGTTTATGCTCCAGAATATTTAACCAAACTTAAGCCCATTCTTACCAAATATTCTGCCAGAGATCTTCAAAATTTAATGTCCTGGAGATTCATAATG"
                        + "GATCTTGTAAGCAGCCTCAGCCGAACCTACAAGGAGTCCAGAAATGCTTTCCGCAAGGCCCTTTATGGTACAACCTCAGAAACAGCAACTTGGAGACGTTGTGCAAACTAT"
                        + "GTCAATGGGAATATGGAAAATGCTGTGGGGAGGCTTTATGTGGAAGCAGCATTTGCTGGAGAGAGTAAACATGTGGTCGAGGATTTGATTGCACAGATCCGAGAAGTTTTT"
                        + "ATTCAGACTTTAGATGACCTCACTTGGATGGATGCCGAGACAAAAAAGAGAGCTGAAGAAAAGGCCTTAGCAATTAAAGAAAGGATCGGCTATCCTGATGACATTGTTTCA"
                        + "AATGATAACAAACTGAATAATGAGTACCTCGAGTTGAACTACAAAGAAGATGAATACTTCGAGAACATAATTCAAAATTTGAAATTCAGCCAAAGTAAACAACTGAAGAAG"
                        + "CTCCGAGAAAAGGTGGACAAAGATGAGTGGATAAGTGGAGCAGCTGTAGTCAATGCATTTTACTCTTCAGGAAGAAATCAGATAGTCTTCCCAGCCGGCATTCTGCAGCCC"
                        + "CCCTTCTTTAGTGCCCAGCAGTCCAACTCATTGAACTATGGGGGCATCGGCATGGTCATAGGACACGAAATCACCCATGGCTTCGATGACAATGGCAGAAACTTTAACAAA"
                        + "GATGGAGACCTCGTTGACTGGTGGACTCAACAGTCTGCAAGTAACTTTAAGGAGCAATCCCAGTGCATGGTGTATCAGTATGGAAACTTTTCCTGGGACCTGGCAGGTGGA"
                        + "CAGCACCTTAATGGAATTAATACACTGGGAGAAAACATTGCTGATAATGGAGGTCTTGGTCAAGCATACAGAGCCTATCAGAATTATATTAAAAAGAATGGCGAAGAAAAA"
                        + "TTACTTCCTGGACTTGACCTAAATCACAAACAACTATTTTTCTTGAACTTTGCACAGGTGTGGTGTGGAACCTATAGGCCAGAGTATGCGGTTAACTCCATTAAAACAGAT"
                        + "GTGCACAGTCCAGGCAATTTCAGGATTATTGGGACTTTGCAGAACTCTGCAGAGTTTTCAGAAGCCTTTCACTGCCGCAAGAATTCATACATGAATCCAGAAAAGAAGTGC"
                        + "CGGGTTTGGTGATCTTCAAAAGAAGCATTGCAGCCCTTGGCTAGACTTGCCAACACCACAGAAATGGGGAATTCTCTAATCGAAAGAAAATGGGCCCTAGGGGTCACTGTA"
                        + "CTGACTTGAGGGTGATTAACAGAGAGGGCACCATCACAATACAGATAACATTAGGTTGTCCTAGAAAGGGTGTGGAGGGAGGAAGGGGGTCTAAGGTCTATCAAGTCAATC"
                        + "ATTTCTCACTGTGTACATAATGCTTAATTTCTAAAGATAATATTACTGTTTATTTCTGTTTCTCATATGGTCTACCAGTTTGCTGATGTCCCTAGAAAACAATGCAAAACC"
                        + "TTTGAGGTAGACCAGGATTTCTAATCAAAAGGGAAAAGAAGATGTTGAAGAATACAGTTAGGCACCAGA";

        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void testReverseStrand() throws Exception {

//         14086   X:109669061:-:T X       109669061       -       T       indel   ENSP00000423539 p.Tyr19IlefsTer2        p.Gly18fs
//        fs_shorthand_diff_pos



        Gene gene = getGene("ENSG00000068366");
        Transcript transcript = getTranscript(gene, "ENST00000514500");
        // Chromosome X: 109,644,026-109,669,109
        Variant variant = new Variant("X",
                109669061,
                "-",
                "T");

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);
        String originalTranscriptSequence = transcript.getcDnaSequence();

        // AAACTCTGTTCAAGATAGGGTATGATTACAAATTGGAACAGATCAAAAAGGGATATGATGCACCTCTTTGCAATCTGTTACTGTTTAAAAAGGTCAAGGCCCTGCTGGGAGGGAATGTCCGCATGATGCTGTCTGGAGGGGCCCCGCTATCTCCTCAGACACACCGATTCATGAATGTCTGCTTCTGCTGCCCAATTGGCCAGGGTTATGGACTGACAGAATCATGTGGTGCTGGGACAGTTACTGAAGTAACTGACTATACTACTGGCAGAGTTGGAGCACCTCTTATTTGCTGTGAAATTAAGCTAAAAGACTGGCAAGAAGGCGGTTATACAATTAATGACAAGCCAAACCCCAGAGGTGAAATCGTAATTGGTGGACAGAACATCTCCATGGGATATTTTAAAAATGAAGAGAAAACAGCAGAAGATTATTCTGTGGATGAAAATGGACAAAGGAACTTGGGTTGATATCTGCAATAATCCTGCTATGGAAGCTGAAATACTGAAAGAAATTCGAGAAGCTGCAAATGCCATGAAATTGGAGCGATTTGAAATTCCAATCAAGGTTCGATTAAGCCCAGAGCCATGGACCCCTGAAACTGGTTTGGTAACTGATGCTTTCAAACTGAAAAGGAAGGAGCTGAGGAACCATTACCTCAAAGACATTGAACGAATGTATGGGGGCAAATAAAAT

        String expected =
                "AATACTCTGTTCAAGATAGGGTATGATTACAAATTGGAACAGATCAAAAAGGGATATGATGCACCTCTTTGCAATCTGTTACTGTTTAAAAAGGTCAAGGCCCTGCTGGGAGGGAATGTCC"
                        + "GCATGATGCTGTCTGGAGGGGCCCCGCTATCTCCTCAGACACACCGATTCATGAATGTCTGCTTCTGCTGCCCAATTGGCCAGGGTTATGGACTGACAGAATCATGTGGTG"
                        + "CTGGGACAGTTACTGAAGTAACTGACTATACTACTGGCAGAGTTGGAGCACCTCTTATTTGCTGTGAAATTAAGCTAAAAGACTGGCAAGAAGGCGGTTATACAATTAATG"
                        + "ACAAGCCAAACCCCAGAGGTGAAATCGTAATTGGTGGACAGAACATCTCCATGGGATATTTTAAAAATGAAGAGAAAACAGCAGAAGATTATTCTGTGGATGAAAATGGAC"
                        + "AAAGGAACTTGGGTTGATATCTGCAATAATCCTGCTATGGAAGCTGAAATACTGAAAGAAATTCGAGAAGCTGCAAATGCCATGAAATTGGAGCGATTTGAAATTCCAATC"
                        + "AAGGTTCGATTAAGCCCAGAGCCATGGACCCCTGAAACTGGTTTGGTAACTGATGCTTTCAAACTGAAAAGGAAGGAGCTGAGGAACCATTACCTCAAAGACATTGAACGA"
                        + "ATGTATGGGGGCAAATAAAAT";

        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);

        Assert.assertEquals("TYR", predictor.buildingComponents.getAlternate());

        Assert.assertEquals("ENSP00000423539:p.Tyr19IlefsTer2", predictor.calculate());
    }

    @Test
    public void test3() throws Exception {

        //        14085   X:109669061:-:T X       109669061       -       T       indel   ENSP00000262835 p.Tyr374IlefsTer2       p.Tyr374fs      fs_shorthand_same_pos
//        14086   X:109669061:-:T X       109669061       -       T       indel   ENSP00000423539 p.Tyr19IlefsTer2        p.Gly18fs       fs_shorthand_diff_pos
//        14087   X:109669061:-:T X       109669061       -       T       indel   ENSP00000339787 p.Tyr415IlefsTer2       p.Tyr415fs      fs_shorthand_same_pos
//        14088   X:109669061:-:T X       109669061       -       T       indel   ENSP00000419171 p.Tyr415IlefsTer2       p.Tyr415fs      fs_shorthand_same_pos

        Gene gene = getGene("ENSG00000008710");
        Transcript transcript = getTranscript(gene, "ENST00000487932");
        Variant variant = new Variant("X",
                109669061,
                "-",
                "T");

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);

        String expected =
                "TCCCACACCCGGCCTGCACTTGGTCACCATGACGGCAGGGAACCCGCTGGGCTCAGCCAACGCCACCGTGGAAGTGGATGTGCAGGTGCCTGTGAGTGGCCTCAGCATCAGGGCCAGCGAG"
                        + "CCCGGAGGCAGCTTCGTGGCGGCCGGGTCCTCTGTGCCCTTTTGGGGGCAGCTGGCCACGGGCACCAATGTGAGCTGGTGCTGGGCTGTGCCCGGCGGCAGCAGCAAGCGT"
                        + "GGCCCTCATGTCACCATGGTCTTCCCGGATGCTGGCACCTTCTCCATCCGGCTCAATGCCTCCAACGCAGTCAGCTGGGTCTCAGCCACGTACAACCTCACGGCGGAGGAG"
                        + "CCCATCGTGGGCCTGGTGCTGTGGGCCAGCAGCAAGGTGGTGGCGCCCGGGCAGCTGGTCCATTTTCAGATCCTGCTGGCTGCCGGCTCAGCTGTCACCTTCCGCCTGCAG"
                        + "GTCGGCGGGGCCAACCCCGAGGTGCTCCCCGGGCCCCGTTTCTCCCACAGCTTCCCCCGCGTCGGAGACCACGTGGTGAGCGTGCGGGGCAAAAACCACGTGAGCTGGGCC"
                        + "CAGGCGCAGGTGCGCATCGTGGTGCTGGAGGCCGTGAGTGGGCTGCAGGTGCCCAACTGCTGCGAGCCTGGCATCGCCACGGGCACTGAGAGGAACTTCACAGCCCGCGTG"
                        + "CAGCGCGGCTCTCGGGTCGCCTACGCCTGGTACTTCTCGCTGCAGAAGGTCCAGGGCGACTCGCTGGTCATCCTGTCGGGCCGCGACGTCACCTACACGCCCGTGGCCGCG"
                        + "GGGCTGTTGGAGATCCAGGTGCGCGCCTTCAACGCCCTGGGCAGTGAGAACCGCACGCTGGTGCTGGAGGTTCAGGACGCCGTCCAGTATGTGGCCCTGCAGAGCGGCCCC"
                        + "TGCTTCACCAACCGCTCGGCGCAGTTTGAGGCCGCCACCAGCCCCAGCCCCCGGCGTGTGGCCTACCACTGGGACTTTGGGGATGGGTCGCCAGGGCAGGACACAGATGAG"
                        + "CCCAGGGCCGAGCACTCCTACCTGAGGCCTGGGGACTACCGCGTGCAGGTGAACGCCTCCAACCTGGTGAGCTTCTTCGTGGCGCAGGCCACGGTGACCGTCCAGGTGCTG"
                        + "GCCTGCCGGGAGCCGGAGGTGGACGTGGTCCTGCCCCTGCAGGTGCTGATGCGGCGATCACAGCGCAACTACTTGGAGGCCCACGTTGACCTGCGCGACTGCGTCACCTAC"
                        + "CAGACTGAGTACCGCTGGGAGGTGTATCGCACCGCCAGCTGCCAGCGGCCGGGGCGCCCAGCGCGTGTGGCCCTGCCCGGCGTGGACGTGAGCCGGCCTCGGCTGGTGCTG"
                        + "CCGCGGCTGGCGCTGCCTGTGGGGCACTACTGCTTTGTGTTTGTCGTGTCATTTGGGGACACGCCACTGACACAGAGCATCCAGGCCAATGTGACGGTGGCCCCCGAGCGC"
                        + "CTGGTGCCCATCATTGAGGGTGGCTCATACCGCGTGTGGTCAGACACACGGGACCTGGTGCTGGATGGGAGCGAGTCCTACGACCCCAACCTGGAGGACGGCGACCAGACG"
                        + "CCGCTCAGTTTCCACTGGGCCTGTGTGGCTTCGACACAGAGGGAGGCTGGCGGGTGTGCGCTGAACTTTGGGCCCCGCGGGAGCAGCACGGTCACCATTCCACGGGAGCGG"
                        + "CTGGCGGCTGGCGTGGAGTACACCTTCAGCCTGACCGTGTGGAAGGCCGGCCGCAAGGAGGAGGCCACCAACCAGACGGTGCTGATCCGGAGTGGCCGGGTGCCCATTGTG"
                        + "TCCTTGGAGTGTGTGTCCTGCAAGGCACAGGCCGTGTACGAAGTGAGCCGCAGCTCCTACGTGTACTTGGAGGGCCGCTGCCTCAATTGCAGCAGCGGCTCCAAGCGAGGG"
                        + "CGGTGGGCTGCACGTACGTTCAGCAACAAGACGCTGGTGCTGGATGAGACCACCACATCCACGGGCAGTGCAGGCATGCGACTGGTGCTGCGGCGGGGCGTGCTGCGGGAC"
                        + "GGCGAGGGATACACCTTCACGCTCACGGTGCTGGGCCGCTCTGGCGAGGAGGAGGGCTGCGCCTCCATCCGCCTGTCCCCCAACCGCCCGCCGCTGGGGGGCTCTTGCCGC"
                        + "CTCTTCCCACTGGGCGCTGTGCACGCCCTCACCACCAAGGTGCACTTCGAATGCACGGGCTGGCATGACGCGGAGGATGCTGGCGCCCCGCTGGTGTACGCCCTGCTGCTG"
                        + "CGGCGCTGTCGCCAGGGCCACTGCGAGGAGTTCTGTGTCTACAAGGGCAGCCTCTCCAGCTACGGAGCCGTGCTGCCCCCGGGTTTCAGGCCACACTTCGAGGTGGGCCTG"
                        + "GCCGTGGTGGTGCAGGACCAGCTGGGAGCCGCTGTGGTCGCCCTCAACAGGTCTTTGGCCATCACCCTCCCAGAGCCCAACGGCAGCGCAACGGGGCTCACAGTCTGGCTG"
                        + "CACGGGCTCACCGCTAGTGTGCTCCCAGGGCTGCTGCGGCAGGCCGATCCCCAGCACGTCATCGAGTACTCGTTGGCCCTGGTCACCGTGCTGAACGAGTACGAGCGGGCC"
                        + "CTGGACGTGGCGGCAGAGCCCAAGCACGAGCGGCAGCACCGAGCCCAGATACGCAAGAACATCACGGAGACTCTGGTGTCCCTGAGGGTCCACACTGTGGATGACATCCAG"
                        + "CAGATCGCTGCTGCGCTGGCCCAGTGCATGGGGCCCAGCAGGGAGCTCGTATGCCGCTCGTGCCTGAAGCAGACGCTGCACAAGCTGGAGGCCATGATGCTCATCCTGCAG"
                        + "GCAGAGACCACCGCGGGCACCGTGACGCCCACCGCCATCGGAGACAGCATCCTCAACATCACAGGAGACCTCATCCACCTGGCCAGCTCGGACGTGCGGGCACCACAGCCC"
                        + "TCAGAGCTGGGAGCCGAGTCACCATCTCGGATGGTGGCGTCCCAGGCCTACAACCTGACCTCTGCCCTCATGCGCATCCTCATGCGCTCCCGCGTGCTCAACGAGGAGCCC"
                        + "CTGACGCTGGCGGGCGAGGAGATCGTGGCCCAGGGCAAGCGCTCGGACCCGCGGAGCCTGCTGTGCTATGGCGGCGCCCCAGGGCCTGGCTGCCACTTCTCCATCCCCGAG"
                        + "GCTTTCAGCGGGGCCCTGGCCAACCTCAGTGACGTGGTGCAGCTCATCTTTCTGGTGGACTCCAATCCCTTTCCCTTTGGCTATATCAGCAACTACACCGTCTCCACCAAG"
                        + "CTCCGCCAACTCCGCCAACTCCGTTGTGGTCCAGCCCCAGGCCTCCGTCGGTGCTGTGGTCACCCTGGACAGCAGCAACCCTGCGGCCGGGCTGCATCTGCAGCTCAACTA"
                        + "TACGCTGCTGGACGGCCACTACCTGTCTGAGGAACCTGAGCCCTACCTGGCAGTCTACCTACACTCGGAGCCCCGGCCCAATGAGCACAACTGCTCGGCTAGCAGGAGGAT"
                        + "CCGCCCAGAGTCACTCCAGGGTGCTGACCACCGGCCCTACACCTTCTTCATTTCCCCGGGGAGCAGAGACCCAGCGGGGAGTTACCATCTGAACCTCTCCAGCCACTTCCG"
                        + "CTGGTCGGCGCTGCAGGTGTCCGTGGGCCTGTACACGTCCCTGTGCCAGTACTTCAGCGAGGAGGACATGGTGTGGCGGACAGAGGGGCTGCTGCCCCTGGAGGAGACCTC"
                        + "GCCCCGCCAGGCCGTCTGCCTCACCCGCCACCTCACCGCCTTCGGCGCCAGCCTCTTCGTGCCCCCAAGCCATGTCCGCTTTGTGTTTCCTGAGCCGACAGCGGATGTAAA"
                        + "CTACATCGTCATGCTGACATGTGCTGTGTGCCTGGTGACCTACATGGTCATGGCCGCCATCCTGCACAAGCTGGACCAGTTGGATGCCAGCCGGGGCCGCGCCATCCCTTT"
                        + "CTGTGGGCAGCGGGGCCGCTTCAAGTACGAGATCCTCGTCAAGACAGGCTGGGGCCGGGGCTCAGGTACCACGGCCCACGTGGGCATCATGCTGTATGGGGTGGACAGCCG"
                        + "GAGCGGCCACCGGCACCTGGACGGCGACAGAGCCTTCCACCGCAACAGCCTGGACATCTTCCGGATCGCCACCCCGCACAGCCTGGGTAGCGTGTGGAAGATCCGAGTGTG"
                        + "GCACGACAACAAAGGGCTCAGCCCTGCCTGGTTCCTGCAGCACGTCATCGTCAGGGACCTGCAGACGGCACGCAGCGCCTTCTTCCTGGTCAATGACTGGCTTTCGGTGGA"
                        + "GACGGAGGCCAACGGGGGCCTGGTGGAGAAGGAGGTGCTGGCCGCGAGCGACGCAGCCCTTTTGCGCTTCCGGCGCCTGCTGGTGGCTGAGCTGCAGCGTGGCTTCTTTGA"
                        + "CAAGCACATCTGGCTCTCCATATGGGACCGGCCGCCTCGTAGCCGTTTCACTCGCATCCAGAGGGCCACCTGCTGCGTTCTCCTCATCTGCCTCTTCCTGGGCGCCAACGC"
                        + "CGTGTGGTACGGGGCTGTTGGCGACTCTGCCTACAGCACGGGGCATGTGTCCAGGCTGAGCCCGCTGAGCGTCGACACAGTCGCTGTTGGCCTGGTGTCCAGCGTGGTTGT"
                        + "CTATCCCGTCTACCTGGCCATCCTTTTTCTCTTCCGGATGTCCCGGAGCAAGGTGGCTGGGAGCCCGAGCCCCACACCTGCCGGGCAGCAGGTGCTGGACATCGACAGCTG"
                        + "CCTGGACTCGTCCGTGCTGGACAGCTCCTTCCTCACGTTCTCAGGCCTCCACGCTGAGCAGGCCTTTGTTGGACAGATGAAGAGTGACTTGTTTCTGGATGATTCTAAGAG"
                        + "TCTGGTGTGCTGGCCCTCCGGCGAGGGAACGCTCAGTTGGCCGGACCTGCTCAGTGACCCGTCCATTGTGGGTAGCAATCTGCGGCAGCTGGCACGGGGCCAGGCGGGCCA"
                        + "TGGGCTGGGCCCAGAGGAGGACGGCTTCTCCCTGGCCAGCCCCTACTCGCCTGCCAAATCCTTCTCAGCATCAGATGAAGACCTGATCCAGCAGGTCCTTGCCGAGGGGGT"
                        + "CAGCAGCCCAGCCCCTACCCAAGACACCCACATGGAAACGGACCTGCTCAGCAGCCTGTCCAGCACTCCTGGGGAGAAGACAGAGACGCTGGCGCTGCAGAGGCTGGGGGA"
                        + "GCTGGGGCCACCCAGCCCAGGCCTGAACTGGGAACAGCCCCAGGCAGCGAGGCTGTCCAGGACAGGACTGGTGGAGGGTCTGCGGAAGCGCCTGCTGCCGGCCTGGTGTGC"
                        + "CTCCCTGGCCCACGGGCTCAGCCTGCTCCTGGTGGCTGTGGCTGTGGCTGTCTCAGGGTGGGTGGGTGCGAGCTTCCCCCCGGGCGTGAGTGTTGCGTGGCTCCTGTCCAG"
                        + "CAGCGCCAGCTTCCTGGCCTCATTCCTCGGCTGGGAGCCACTGAAGGTCTTGCTGGAAGCCCTGTACTTCTCACTGGTGGCCAAGCGGCTGCACCCGGATGAAGATGACAC"
                        + "CCTGGTAGAGAGCCCGGCTGTGACGCCTGTGAGCGCACGTGTGCCCCGCGTACGGCCACCCCACGGCTTTGCACTCTTCCTGGCCAAGGAAGAAGCCCGCAAGGTCAAGAG"
                        + "GCTACATGGCATGCTGCGGAGCCTCCTGGTGTACATGCTTTTTCTGCTGGTGACCCTGCTGGCCAGCTATGGGGATGCCTCATGCCATGGGCACGCCTACCGTCTGCAAAG"
                        + "CGCCATCAAGCAGGAGCTGCACAGCCGGGCCTTCCTGGCCATCACGCGGTCTGAGGAGCTCTGGCCATGGATGGCCCACGTGCTGCTGCCCTACGTCCACGGGAACCAGTC"
                        + "CAGCCCAGAGCTGGGGCCCCCACGGCTGCGGCAGGTGCGGCTGCAGGAAGCACTCTACCCAGACCCTCCCGGCCCCAGGGTCCACACGTGCTCGGCCGCAGGAGGCTTCAG"
                        + "CACCAGCGATTACGACGTTGGCTGGGAGAGTCCTCACAATGGCTCGGGGACGTGGGCCTATTCAGCGCCGGATCTGCTGGGGGCATGGTCCTGGGGCTCCTGTGCCGTGTA"
                        + "TGACAGCGGGGGCTACGTGCAGGAGCTGGGCCTGAGCCTGGAGGAGAGCCGCGACCGGCTGCGCTTCCTGCAGCTGCACAACTGGCTGGACAACAGGAGCCGCGCTGTGTT"
                        + "CCTGGAGCTCACGCGCTACAGCCCGGCCGTGGGGCTGCACGCCGCCGTCACGCTGCGCCTCGAGTTCCCGGCGGCCGGCCGCGCCCTGGCCGCCCTCAGCGTCCGCCCCTT"
                        + "TGCGCTGCGCCGCCTCAGCGCGGGCCTCTCGCTGCCTCTGCTCACCTCGGTGTGCCTGCTGCTGTTCGCCGTGCACTTCGCCGTGGCCGAGGCCCGTACTTGGCACAGGGA"
                        + "AGGGCGCTGGCGCGTGCTGCGGCTCGGAGCCTGGGCGCGGTGGCTGCTGGTGGCGCTGACGGCGGCCACGGCACTGGTACGCCTCGCCCAGCTGGGTGCCGCTGACCGCCA"
                        + "GTGGACCCGTTTCGTGC";

        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void testPosStrand() throws Exception {
        Gene gene = getGene("ENSG00000121207");
        Transcript transcript = getTranscript(gene, "ENST00000507827");
        Variant variant = new Variant("4",
                154744350,
                "-",
                "CTTCATGGAAGAACCC");

        // 154744331 = cDNA 67 = 86 cDNA

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);

       // reference
        String reference =
                "ACAGAATGTAGCCACCTTTCTTAACGGTCCGGGAAACCAGAGGTCTCTCCAGCTACTCAGGGATGAAGAACCCCATGCTGGAGGTGGTGTCTTTACTACTGGAGAAGCTGCTCCTCATCTCCAACTTCACGCTCTTTAGTTCGGGCGCCGCGGGCGAAGACAAAGGGAGGAACAGTTTTTATGAAACCAGCTCTTTCCACCGAGGCGACGTGCTGGAGGTGCCCCGGACCCACCTGACCCACTATGGCATCTACCTAGGAGACAACCGTGTTGCCCACATGATGCCCGACATCCTGTTGGCCCTGACAGACGACATGGGGCGCACGCAGAAGGTGGTCTCCAACAAGCGTCTCATCCTGGGCGTTATTGTCAAAGTGGCCAGCATCCGCGTGGACACAGTGGAGGACTTCGCCTACGGAGCTAACATCCTGGTCAATCACCTGGACGAGTCCCTCCAGAAAAAGGCACTGCTCAACGAGGAGGTGGCGCGGAGGGCTGAAAAGCTGCTGGGCTTTACCCCCTACAGCCTGCTGTGGAACAACTGCGAGCACTTCGTGACCTACTGCAGATATGGCACCCCGATCAGTCCCCAGTCCGACAAGTTTTGTGAGACTGTGAAGATAATTATTCGTGATCAGAGAAGTGTTCTTGCTTCAGCAGTCTTGGGATTGGCGTCTATAGTCTGTACGGGCTTGGTATCATACACTACCCTTCCTGCAATTTTTATTCCATTCTTCCTATGGATGGCTGGCTAACTTCATACCCCCATGTCAGTGTGTGTATTCTGTATGTAAATATGTTTATATTTATAGAGCATCAATCAATATAAGCATTATTGAGAAAAATGTGACCCGTAACACTGTGTTCTGGATAAAAATGTGATTAGGAATCACGCAAAGTGCTTACTGTGTAAGCCCAAGAACAAAGGCTTTCTGAATCTTCTCAGGCAGTTCAGATTTAAAGCACCATCCAAACCTTGGAAATACGACAGGGTGTGGTAGAATTCAGCAATATGAGAAAACCAGCCCCTAAAATGATAGCCACAAGAGATTAATTGTGTTTTTTTTTCTCCTGTAATCCTTGTACTGTTCGGCTGAATTTGAAGATTGGAAGACTTATATTGAGACCAGTAACTTTACTGTAAATTTACTTTGTTTCATTGAAAAAACAAATTGATAAACATATTAAACTGGAAGAATTTTCTTTATTCAAATGAAAACATGTTTGATGACTGGTCAAAAAATAAGCTCATAATCTATTTTTTTCATGTAGTATATAAGTCAAGAATGTTTTATTGTCATTATGTGAAACCAATATTGGCAAATAGTACTTTAATGATGAAGTAAATGACCAGAAATTATAGAAATCTGTGTTTTCCTGTAAAAATAGCACTATAGTATCACTTGAACAATTTGATTTGGCTTTACTTACTAGGAAGCCTGGAATTCATTATTTTTTTCCTTTTATGTGCCACTGTGGCTACTTTAAATCACTCTGAGAGGTAAATGGATATAGGATTGAAGTTATGTGGGTATTTGGCATGTGTGTGTGAAATAAATATGTAGATAGTCACATATACACAGACTGAGAGATAAATTGTTCTTGATTGCTTTATTATCATCATACTAGTGTGTTCATTATAGAGTATCTGTAGAGGTGAATGTAAAAGTAAGTCCAATCTATTTTCTTATGTCATTGAATTTGTAGTGTTAACTTGCATATATGTTATTGGATGGGTTGTCTTTTAAAGCATTTACTAATGTACTCTGAAATTTTTAAAAGCCTTCAGATTTGTTTTCTAGTCACTTTTTTCCATATCATTTCTAATTATAGTTTATATCCTTAAAAGAAGGATGCCACAGTAGTATGTAAAACCCAAACAAGTAGAACCCAAGCAAATAAAATTATTTAAAATAATTTTAAAGTGGCTTAGTACTGCCAGTCATGTAAATTGATTCTGCTGAGGGTCTTATAAGAATTGAGATATAACAATGGTAAAACAAGCATTCAAGCACTTTTACAAAATTACCAAATTCTTAAAATGAAGCCACAGCTAGACTTGCATTTCAGGTATTAAAATTGCTTTCTTAACTGTCAAGAATCACAAAATAACAAATCATATTATGAGTGAATATGGGGAGGGCGGGGCCAATCAGTCAATGATAATCTGAACAAATTTTAAGAGCAGATTTTAGATTAATAATGTTTTATCACCACTAATTTGCCCACAACAAACTCAGTATTTAATTTTTCAAATTAAATATTAAATTATTTAAGTATTTTAAATAATTAAAACATTAAATGGCAACACCATAGAATATAGGTGTTCTCTGGACCTATTCTAACCACTTAAAATTATCTTAAGTATGCATACATAAAAGCAACCACTATGAGAACTACCGTGTTAGTGGTTTTTCACTTACTGTATATTACCCTTGTAGGAATAGTTTAAGGAAATTCATTTCTTAAAAATATAGTGTCCTCAAATAATTAATTTTTTTGCAAACTTTAGTTATTACAGGCAGCAAAAACCACTGTCTGAAACTAAATCTGTGTTCAAAGATGAAGACCCCTCATTAAAAGCCAAGGACGTTCTTAAGATTGGAACTGACATAATTAGTCTTGACTTACTTCATTAAAGCAAGATTCAATTC";

        String expected =
                "ACAGAATGTAGCCACCTTTCTTAACGGTCCGGGAAACCAGAGGTCTCTCCAGCTACTCAGGGATGAAGAACCCCATGCTGGAGGTCTTCATGGAAGAACCCGGTGTCTTTACTACTGGAGAAGCTGCTCCTCATCTCCAACTTCACGCTCTTTAGTTCGGGCGCCGCGGGCGAAGACAAAGGGAGGAACAGTTTTTATGAAACCAGCTCTTTCCACCGAGGCGACGTGCTGGAGGTGCCCCGGACCCACCTGACCCACTATGGCATCTACCTAGGAGACAACCGTGTTGCCCACATGATGCCCGACATCCTGTTGGCCCTGACAGACGACATGGGGCGCACGCAGAAGGTGGTCTCCAACAAGCGTCTCATCCTGGGCGTTATTGTCAAAGTGGCCAGCATCCGCGTGGACACAGTGGAGGACTTCGCCTACGGAGCTAACATCCTGGTCAATCACCTGGACGAGTCCCTCCAGAAAAAGGCACTGCTCAACGAGGAGGTGGCGCGGAGGGCTGAAAAGCTGCTGGGCTTTACCCCCTACAGCCTGCTGTGGAACAACTGCGAGCACTTCGTGACCTACTGCAGATATGGCACCCCGATCAGTCCCCAGTCCGACAAGTTTTGTGAGACTGTGAAGATAATTATTCGTGATCAGAGAAGTGTTCTTGCTTCAGCAGTCTTGGGATTGGCGTCTATAGTCTGTACGGGCTTGGTATCATACACTACCCTTCCTGCAATTTTTATTCCATTCTTCCTATGGATGGCTGGCTAACTTCATACCCCCATGTCAGTGTGTGTATTCTGTATGTAAATATGTTTATATTTATAGAGCATCAATCAATATAAGCATTATTGAGAAAAATGTGACCCGTAACACTGTGTTCTGGATAAAAATGTGATTAGGAATCACGCAAAGTGCTTACTGTGTAAGCCCAAGAACAAAGGCTTTCTGAATCTTCTCAGGCAGTTCAGATTTAAAGCACCATCCAAACCTTGGAAATACGACAGGGTGTGGTAGAATTCAGCAATATGAGAAAACCAGCCCCTAAAATGATAGCCACAAGAGATTAATTGTGTTTTTTTTTCTCCTGTAATCCTTGTACTGTTCGGCTGAATTTGAAGATTGGAAGACTTATATTGAGACCAGTAACTTTACTGTAAATTTACTTTGTTTCATTGAAAAAACAAATTGATAAACATATTAAACTGGAAGAATTTTCTTTATTCAAATGAAAACATGTTTGATGACTGGTCAAAAAATAAGCTCATAATCTATTTTTTTCATGTAGTATATAAGTCAAGAATGTTTTATTGTCATTATGTGAAACCAATATTGGCAAATAGTACTTTAATGATGAAGTAAATGACCAGAAATTATAGAAATCTGTGTTTTCCTGTAAAAATAGCACTATAGTATCACTTGAACAATTTGATTTGGCTTTACTTACTAGGAAGCCTGGAATTCATTATTTTTTTCCTTTTATGTGCCACTGTGGCTACTTTAAATCACTCTGAGAGGTAAATGGATATAGGATTGAAGTTATGTGGGTATTTGGCATGTGTGTGTGAAATAAATATGTAGATAGTCACATATACACAGACTGAGAGATAAATTGTTCTTGATTGCTTTATTATCATCATACTAGTGTGTTCATTATAGAGTATCTGTAGAGGTGAATGTAAAAGTAAGTCCAATCTATTTTCTTATGTCATTGAATTTGTAGTGTTAACTTGCATATATGTTATTGGATGGGTTGTCTTTTAAAGCATTTACTAATGTACTCTGAAATTTTTAAAAGCCTTCAGATTTGTTTTCTAGTCACTTTTTTCCATATCATTTCTAATTATAGTTTATATCCTTAAAAGAAGGATGCCACAGTAGTATGTAAAACCCAAACAAGTAGAACCCAAGCAAATAAAATTATTTAAAATAATTTTAAAGTGGCTTAGTACTGCCAGTCATGTAAATTGATTCTGCTGAGGGTCTTATAAGAATTGAGATATAACAATGGTAAAACAAGCATTCAAGCACTTTTACAAAATTACCAAATTCTTAAAATGAAGCCACAGCTAGACTTGCATTTCAGGTATTAAAATTGCTTTCTTAACTGTCAAGAATCACAAAATAACAAATCATATTATGAGTGAATATGGGGAGGGCGGGGCCAATCAGTCAATGATAATCTGAACAAATTTTAAGAGCAGATTTTAGATTAATAATGTTTTATCACCACTAATTTGCCCACAACAAACTCAGTATTTAATTTTTCAAATTAAATATTAAATTATTTAAGTATTTTAAATAATTAAAACATTAAATGGCAACACCATAGAATATAGGTGTTCTCTGGACCTATTCTAACCACTTAAAATTATCTTAAGTATGCATACATAAAAGCAACCACTATGAGAACTACCGTGTTAGTGGTTTTTCACTTACTGTATATTACCCTTGTAGGAATAGTTTAAGGAAATTCATTTCTTAAAAATATAGTGTCCTCAAATAATTAATTTTTTTGCAAACTTTAGTTATTACAGGCAGCAAAAACCACTGTCTGAAACTAAATCTGTGTTCAAAGATGAAGACCCCTCATTAAAAGCCAAGGACGTTCTTAAGATTGGAACTGACATAATTAGTCTTGACTTACTTCATTAAAGCAAGATTCAATTC";

        String proteinSequence =
                "MKNPMLEVVSLLLEKLLLISNFTLFSSGAAGEDKGRNSFYETSSFHRGDVLEVPRTHLTHYGIYLGDNRVAHMMPDILLALTDDMGRTQKVVSNKRLILGVIVKVASIRVDTVEDFAYGAN"
                        + "ILVNHLDESLQKKALLNEEVARRAEKLLGFTPYSLLWNNCEHFVTYCRYGTPISPQSDKFCETVKIIIRDQRSVLASAVLGLASIVCTGLVSYTTLPAIFIPFFLWMAG";

        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);

        Assert.assertEquals("PHE", predictor.buildingComponents.getAlternate());

        // Val9PhefsTer23
        Assert.assertEquals("ENSP00000426761:p.Val9PhefsTer23", predictor.calculate());
    }


// 32102   4:154744350:-:CTTCATGGAAGAACCC  4       154744350       -       CTTCATGGAAGAACCC        indel   ENSP00000426761 p.Val9PhefsTer23        p.Val9fs        fs_shorthand_same_pos
//32103   4:154744350:-:CTTCATGGAAGAACCC  4       154744350       -       CTTCATGGAAGAACCC        indel   ENSP00000337224 p.Val9PhefsTer23        p.Val9fs        fs_shorthand_same_pos
// 32104   4:154744350:-:CTTCATGGAAGAACCC  4       154744350       -       CTTCATGGAAGAACCC        indel   ENSP00000422324 p.Val9PhefsTer23        p.Val9fs        fs_shorthand_same_pos

    @Test
    public void testRightAlign() throws Exception {
        Gene gene = getGene("ENSG00000221859");
        Transcript transcript = getTranscript(gene, "ENST00000380095");
        Variant variant = new Variant("21",
                46057614,
                "TGC",
                "-");

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);
        String expected =
                "CACTCACTCACACACTCACTCACTCACACACCTCCCCCAGCTCACCGCCTCCCCACTCCAGCATGGCCGCCTCCACCATGTCCATCTGCTCCAGCGCCTGCACTGACTCTTGGCGGGTAGTCGACTGCCCAGAGAGCTGCTGCGAGCCCTGCTGCTGTGCCCCAGCCCCCAGCTTGACCCTGGTCTGCACCCCAGTGAGCTGTGTGTCCAGCCCCTGCTGCCAGACGGCCTGTGAGCCCAGCGCCTGCCAATCAGGCTACACCAGCTCCTGCACAACCCGCTACCAGCAGTCTAGCTGCCAGCCGGATTGCTGCACCTCCTCCCCCTGCCAGCAGGCCTGCTGTGTGCCTGTCTGCTGTGTGCCCGTCTGCTGCGTGCCCGTCTGTAACAAGCCTGTGTGCTTCGTGCCTACCTGCTCCGAGTCTTCCCCTTCATGCTGCCAGCAGTCTAGCTGCCAGCCAACTTGCTGCACCTCCTCCCCATGCCAGCAGGCCTGCTGTGTGCCTGTCTGCTCTAAGTCCGTCTGCTATGTGCCTGTGTGCTCTGGGGCTTCCACTTCATGCTGCCAGCAGTCTAGCTGCCAGCCTGCTTGCTGCACCGCCTCCTGCTGCAGACCCTCCTCCTCCGTGTCCCTCCTCTGCCACCCTGTGTGCAAGTCCACCTGCTGCGTGCCCGTCCCCTCCTGCGGTGCCTCTGCCTCCTCCTGCCAGCCCAGCTGCTGCCGCACGGCCTCCTGTGTTTCCCTCCTCTGCCGCCCCGTGTGCTCCCGCCCTGCCTGCTACAGCCTCTGCTCTGGCCAGAAGTCCAGCTGCTGACAGCCCTGGATGTGATCCGGAGTCCCTTCCCACCAGGGGCTGACCTCCCAGCTGCCCCAGCAAGCTCTGCCCTCTCTGGCTTTGACACCCTCAGAAGGTGGGGCAGGCTCTTTGTCTTGGGGACCAGGATGCTCCCCCAGTCCTTCCCAGATGATGGCTGCCTGTGGGACCCCAGCTACTCCCCCAGACCCAAGTTCTGCAGAACTAACCCCCAGCAGGCCTGGTTCCACCCTGGGCAGCACCCCCTCTAGTTCTAATAAAGCCGCCTCTGTCTCACACC";
        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);

        Assert.assertEquals("ARG", predictor.buildingComponents.getAlternate());


        Assert.assertEquals("ENSP00000369438:p.Cys95del", predictor.calculate());
    }


    // Frameshift on the last aa causes generation of exact same aa followed by stop codon, i.e.
    // original sequence            ......CTGGCT
    // original sequence                        GTAATCAC......
    // codons                             |  |  |  |
    // original aa sequence               T  T  L  STOP
    // sequence after TTAA insertion            ttaaGTAA
    // codons                             |  |  |  |
    // altered aa sequence                T  T  L  STOP
    // Variant validator describes it as a simple frameshift and that's how we're handling it

    @Test
    public void testFrameShift() throws Exception {
        Gene gene = getGene("ENSG00000018408");
        Transcript transcript = getTranscript(gene, "ENST00000465804");
        Variant variant = new Variant("3",
                149238596,
                "-",
                "TTAA");

        // CDS positon 1457


        Assert.assertEquals(400, transcript.getProteinSequence().length());

        Assert.assertEquals("L", String.valueOf(transcript.getProteinSequence().charAt(399)));

        HgvsProteinCalculator predictor = new HgvsProteinCalculator(variant, transcript);

        String proteinSequence = "MNPASAPPPLPPPGQQVIHVTQDLDTDLEALFNSVMNPKPSSWRKKILPESFFKEPDSGSHSRQSSTDSSGGHPGPRLAGGAQHVRSHSSPASLQLGTGAGAAGSPAQQHAHLRQQSYDVTDELPLPPGWEMTFTATGQRYFLNHIEKITTWQDPRKAMNQPLNHMNLHPAVSSTPVPQRSMAVSQPNLVMNHQHQQQMAPSTLSQQNHPTQNPPAGLMSMPNALTTQQQQQQKLRLQRIQMERERIRMRQEELMRQEAALCRQLPMEAETLAPVQAAVNPPTMTPDMRSITNNSSDPFLNGGPYHSREQSTDSGLGLGCYSVPTTPEDFLSNVDEMDTGENAGQTPMNINPQQTRFPDFLDCLPGTNVDLGTLESEDLIPLFNDVESALNKSEPFLTWL";

        String reference = "GACACACTCCTCTACAACACCAGAGACTCCCAAACACAAGGCCTTATATTGACTCATTTCAGCTCACATCCTGGCGACTCTCAAGAGAGAAACCTCAGAGTGACTAAAATCTCCATAATGAGAAGACATGTACATTCAGTATCTATTTTGGCATTTTCCCCAATACATCTCTGCTCATCTGACTCTTATCTTGGCATCTGCTTCCTGGTGGATCTGAACTGACCCATAAGCCACGCTTACTAGTGATTTTCCAGAAGATGAATCCGGCCTCGGCGCCCCCTCCGCTCCCGCCGCCTGGGCAGCAAGTGATCCACGTCACGCAGGACCTAGACACAGACCTCGAAGCCCTCTTCAACTCTGTCATGAATCCGAAGCCTAGCTCGTGGCGGAAGAAGATCCTGCCGGAGTCTTTCTTTAAGGAGCCTGATTCGGGCTCGCACTCGCGCCAGTCCAGCACCGACTCGTCGGGCGGCCACCCGGGGCCTCGACTGGCTGGGGGTGCCCAGCATGTCCGCTCGCACTCGTCGCCCGCGTCCCTGCAGCTGGGCACCGGCGCGGGTGCTGCGGGTAGCCCCGCGCAGCAGCACGCGCACCTCCGCCAGCAGTCCTACGACGTGACCGACGAGCTGCCACTGCCCCCGGGCTGGGAGATGACCTTCACGGCCACTGGCCAGAGGTACTTCCTCAATCACATAGAAAAAATCACCACATGGCAAGACCCTAGGAAGGCGATGAATCAGCCTCTGAATCATATGAACCTCCACCCTGCCGTCAGTTCCACACCAGTGCCTCAGAGGTCCATGGCAGTATCCCAGCCAAATCTCGTGATGAATCACCAACACCAGCAGCAGATGGCCCCCAGTACCCTGAGCCAGCAGAACCACCCCACTCAGAACCCACCCGCAGGGCTCATGAGTATGCCCAATGCGCTGACCACTCAGCAGCAGCAGCAGCAGAAACTGCGGCTTCAGAGAATCCAGATGGAGAGAGAAAGGATTCGAATGCGCCAAGAGGAGCTCATGAGGCAGGAAGCTGCCCTCTGTCGACAGCTCCCCATGGAAGCTGAGACTCTTGCCCCAGTTCAGGCTGCTGTCAACCCACCCACGATGACCCCAGACATGAGATCCATCACTAATAATAGCTCAGATCCTTTCCTCAATGGAGGGCCATATCATTCGAGGGAGCAGAGCACTGACAGTGGCCTGGGGTTAGGGTGCTACAGTGTCCCCACAACTCCGGAGGACTTCCTCAGCAATGTGGATGAGATGGATACAGGAGAAAACGCAGGACAAACACCCATGAACATCAATCCCCAACAGACCCGTTTCCCTGATTTCCTTGACTGTCTTCCAGGAACAAACGTTGACTTAGGAACTTTGGAATCTGAAGACCTGATCCCCCTCTTCAATGATGTAGAGTCTGCTCTGAACAAAAGTGAGCCCTTTCTAACCTGGCTGTAATCACTACCATTGTAACTTGGATGTAGCCATGACCTTACATTTCCTGGGCCTCTTGGAAAAAGTGATGGAGCAGAGCAAGTCTGCAGGTGCACCACTTCCCGCCTCCATGACTCGTGCTCCCTCCTTTTTATGTTGCCAGTTTAATCATTGCCTGGTTTTGATTGAGAGTAACTTAAGTTAAACATAAATAAATATTCTATTTTCATTTTCTGCAAGCCTGCGTTCTTGTGACAGATTATACAGAATTGTGTCTGCAGGATTGATTATGCAGAATACTTTTCTCTTTCTTCTCTGCTGCCCCATGGCTAAGCTTTATGGGTGTTAATTGAAATTTATACACCAATTGATTTTAAACCATAAAAAGCTGACCACAGGCAGTTACTTCTGAGGGCATCTTGGTCCAGGAAATGTGCACAAAATTCGACCTGATTTACAGTTTCAAAAACTGTATTGATGACAGTAGTACCAAATGCTTTAAAAACTATTTAACTTGAGCTTTAAAAATCATTGTATGGATAGTAAAATTCTACTGTATGGAATACAATGTAATTTTGAATCCATGCTGGCTCTGATGGCTCTTATTAGTCTGTATTTATAAAGGCACACAGTCCTATTGTAGCTTATCTTTCGTTATTTTACTGCAGAGCATCTAGACAACTTAGTCCCTCCAGCGGGAAAGTAGCAGCAGCAGCATTAGTCACAGGTCTTACACTACAGATCTTGTGAAAGAGACCAGTTTGGTACTAATTATGAGCATTTTATTCAAACAAAAGTTTTTGAAATATTACAACTGGGGATTTAAAAAATTGCAGCTTAGAATCTGATGGTTTTTTTTTTTCTTGATGTTGTTTGTTTGTTTTTGAGATCGAGTTTTGCTCTTGTTGTCCAGGCTGGAATGCAATGGCACAATCTCGGCTCACTGCAACCTCTGCCTTCTGGGTTCAAGCGATTCTCCTGCCTTAGCCTCCCGAGTAGCTGGGATTACAGGCACCTGCCACCACGTCCGGCTAATTTTTTGTATTTTGAGTAGAGACGGGGTTTCACCATAATGGTCAGGCTGTTCTCAAACTCCTGATCTCAGGTGATCCACCCATCTCGGCCTCCCAAAGTGCTGGGATTACTGGCGTGAGCCACCGCACCCGGCCTTGATGTTTATTTTATAAAGCACTGTAATTTTGTAGCTGATGACAAAAGGCAGCCAAATGTTTTTGATAAATCAGTGGCAACTGTATTTTTGTCTTTTGAAATAACTCTGAAAACATCAGGACAACATAGATTTCAACCTGATAGCACACCACACACAGTGAGCTGTTGCTTTTTAAATTCTGAAGCCTTGTCAGGTTTGCTTCCTAGATTTCAAGTGTTTAAAATAATTCTATCTATGAAACTGAAGGATGAAGCAGATCTCTGACTGACATGTAAAAAAAAATGCCCTTTGAGGGTGTATGGTGGAGATAAATGTTTCTGAATTCAGTAAAATTGATTCCTAAGTATATTATCCTAATCCTGTTTGCTACAGTTGGTATAAAAAGGCATGAAATATGTATTCAATACCTCTTATGTAACCAAAACCATTTTTAATTAGCTTTTAAGGACTGAGAGAGCATCATGTTCAACTGGCATGCAGTCTGCCTGCATTGCCAATGAAGTCCTCAACTGTTTAATATTTTGAACTAATATTATTTATAATCTATGAATTTAATCTTTTTTGAAAGACTTTAATAATTTGAGTCTCTGAGAGGATACTTTCAATTTCCATGGGGGACTTATTTGTTGGGGATCTTAAATAAGATTCCTTTTGATCTACCGGAATATACATGTACAGAGTACATTGGATCATGTTGGAAAGAAGGCAAGTGAAAAGGTCAGAGATGAAGTAGCAAAGTTATGGAATATCGTGGAAAGGATACTAGTTGTGAAATGGAAAGAGACAAGTTATAGTACCCCAAAAGCAAAACAAGCAGGAGATGCAAGAGATGCCCCAAAAGGACAAAGCAACAATTTTCTGTTGCCACCTTTATACCGGAAGACTCTGTTGTAGAAGAAAAGAAGGCTTTGGTGCACCTTATGTGGGAGGAGGAGGGGCAGGGCATGCTGATGCTGAGCGTACAGGCAGACAAGAGCGTAGCCTGCTGTTGCCTCCATCACTATGAAATGACTTATTTTACCTGAAGGACCCATGGTTTATGTTCCTCTAATTCCTTTCACTCTCCCTAAGCCCTCTGAGAGAGATGAAGATAGATGATTTTATTGCTACTAAATTGAAGGGAGCACTATTTCTTTTTGTCTTTTGTTAGCAAAAAATTGCAAAAAGAATTGTACATTCTTGCTAAAAATAAATAAATAAATAAAAAATTAAAAAAACAAGGGACCTAACAAAACTCAGCAGTGTTACTGTATTTTTAAAAAATATTTTTATAGACTCATTTTCAGGTTATTAAATGTAAGAGAAACAGATACCCCTCTTTTTTAAAGTAGGTAAATCATTGATGATTTATATTACCAATTTTTAGAAGTAATTTTCTAGTAAGCTTGTGGCATCAGAAAATACTAGAAGATTTTTTTAGTTAAATTAGTTAGAACATTTATGAATGAATATAATAAATATTTTTTCAGAATAAAATATGGACCCTTTGTGTTTACTAATAGATAAAGCCAGATATAATTTTTTGTTTTTAAGGCCACAAAATATGGCCTTTGTTAAAGAACACTAAAGTTAGAAATCTAAAGTTAGAGCAACTTTTTAATGGCTATTTCCTATTATTGTAAGTGTTAAAACCCCTGCAGAATTCTTGATAAGGTGCTATTTATACTATATTTCTTATTATAAGATAACTGTCTTTAGTCTTCTTAGTACTAGTCTTTTTAGTACTAAATCAATCAGTAAACATCATCATTTCACCCCAAAATTTTGTCACAGAAAAGGCGTATCAAATGAAAAATAATTTCAGAGATCTTTCTTTCAAGATATTTTTTCCTGATAAAATACATTGTCTTGAAGTAAATACATTGTCAAAACCTAATTGCAATTCTGTTAAATCTAAGTAATTTTTAGACAGTGTTTCACCGTATTATTTAGGATGTGAAATGCCATTTCTTTCACTGATTACACCATATACAGGAAACAGGTAAAACAGTGAAAACTTTATTGTGCTGGTTGATGCCAACTTGGTTGAAAAGCTCTCTGCAGAAGAAGTGATCTAGACTGACAGAAGTGTTGCTAATTACAAGTTGTGTTCTCATGACGTAATTAGAAAGTAACTTCTCAAAGTACAACTTTTATGAAAAAAATAAGCTGTTAAAAAAAGGAAATCGTAGGTTAATTTAATTGGGAAAATGGGCAATTGACAGAGACCATTTTCCTAACACATATATGTGCTAGTACTTTAACTTTTTAAAATTTTACTTCTACGTTTTGTAATATAAAAATTTCTATTTTAAGTTTAGAATGTTATACGTACCGAAAGTATGCAGCCAAATCGATCAGATCAAACCATTTTACCTGGAGTTTGGTACTGGTTTTTACTTCTCTGAATCTGTATAAGAAAAATAAAGACAATTGAACTTCCA";

        String expected =
                "GACACACTCCTCTACAACACCAGAGACTCCCAAACACAAGGCCTTATATTGACTCATTTCAGCTCACATCCTGGCGACTCTCAAGAGAGAAACCTCAGAGTGACTAAAATCTCCATAATGAGAAGACATGTACATTCAGTATCTATTTTGGCATTTTCCCCAATACATCTCTGCTCATCTGACTCTTATCTTGGCATCTGCTTCCTGGTGGATCTGAACTGACCCATAAGCCACGCTTACTAGTGATTTTCCAGAAGATGAATCCGGCCTCGGCGCCCCCTCCGCTCCCGCCGCCTGGGCAGCAAGTGATCCACGTCACGCAGGACCTAGACACAGACCTCGAAGCCCTCTTCAACTCTGTCATGAATCCGAAGCCTAGCTCGTGGCGGAAGAAGATCCTGCCGGAGTCTTTCTTTAAGGAGCCTGATTCGGGCTCGCACTCGCGCCAGTCCAGCACCGACTCGTCGGGCGGCCACCCGGGGCCTCGACTGGCTGGGGGTGCCCAGCATGTCCGCTCGCACTCGTCGCCCGCGTCCCTGCAGCTGGGCACCGGCGCGGGTGCTGCGGGTAGCCCCGCGCAGCAGCACGCGCACCTCCGCCAGCAGTCCTACGACGTGACCGACGAGCTGCCACTGCCCCCGGGCTGGGAGATGACCTTCACGGCCACTGGCCAGAGGTACTTCCTCAATCACATAGAAAAAATCACCACATGGCAAGACCCTAGGAAGGCGATGAATCAGCCTCTGAATCATATGAACCTCCACCCTGCCGTCAGTTCCACACCAGTGCCTCAGAGGTCCATGGCAGTATCCCAGCCAAATCTCGTGATGAATCACCAACACCAGCAGCAGATGGCCCCCAGTACCCTGAGCCAGCAGAACCACCCCACTCAGAACCCACCCGCAGGGCTCATGAGTATGCCCAATGCGCTGACCACTCAGCAGCAGCAGCAGCAGAAACTGCGGCTTCAGAGAATCCAGATGGAGAGAGAAAGGATTCGAATGCGCCAAGAGGAGCTCATGAGGCAGGAAGCTGCCCTCTGTCGACAGCTCCCCATGGAAGCTGAGACTCTTGCCCCAGTTCAGGCTGCTGTCAACCCACCCACGATGACCCCAGACATGAGATCCATCACTAATAATAGCTCAGATCCTTTCCTCAATGGAGGGCCATATCATTCGAGGGAGCAGAGCACTGACAGTGGCCTGGGGTTAGGGTGCTACAGTGTCCCCACAACTCCGGAGGACTTCCTCAGCAATGTGGATGAGATGGATACAGGAGAAAACGCAGGACAAACACCCATGAACATCAATCCCCAACAGACCCGTTTCCCTGATTTCCTTGACTGTCTTCCAGGAACAAACGTTGACTTAGGAACTTTGGAATCTGAAGACCTGATCCCCCTCTTCAATGATGTAGAGTCTGCTCTGAACAAAAGTGAGCCCTTTCTAACCTGGCTTTAAGTAATCACTACCATTGTAACTTGGATGTAGCCATGACCTTACATTTCCTGGGCCTCTTGGAAAAAGTGATGGAGCAGAGCAAGTCTGCAGGTGCACCACTTCCCGCCTCCATGACTCGTGCTCCCTCCTTTTTATGTTGCCAGTTTAATCATTGCCTGGTTTTGATTGAGAGTAACTTAAGTTAAACATAAATAAATATTCTATTTTCATTTTCTGCAAGCCTGCGTTCTTGTGACAGATTATACAGAATTGTGTCTGCAGGATTGATTATGCAGAATACTTTTCTCTTTCTTCTCTGCTGCCCCATGGCTAAGCTTTATGGGTGTTAATTGAAATTTATACACCAATTGATTTTAAACCATAAAAAGCTGACCACAGGCAGTTACTTCTGAGGGCATCTTGGTCCAGGAAATGTGCACAAAATTCGACCTGATTTACAGTTTCAAAAACTGTATTGATGACAGTAGTACCAAATGCTTTAAAAACTATTTAACTTGAGCTTTAAAAATCATTGTATGGATAGTAAAATTCTACTGTATGGAATACAATGTAATTTTGAATCCATGCTGGCTCTGATGGCTCTTATTAGTCTGTATTTATAAAGGCACACAGTCCTATTGTAGCTTATCTTTCGTTATTTTACTGCAGAGCATCTAGACAACTTAGTCCCTCCAGCGGGAAAGTAGCAGCAGCAGCATTAGTCACAGGTCTTACACTACAGATCTTGTGAAAGAGACCAGTTTGGTACTAATTATGAGCATTTTATTCAAACAAAAGTTTTTGAAATATTACAACTGGGGATTTAAAAAATTGCAGCTTAGAATCTGATGGTTTTTTTTTTTCTTGATGTTGTTTGTTTGTTTTTGAGATCGAGTTTTGCTCTTGTTGTCCAGGCTGGAATGCAATGGCACAATCTCGGCTCACTGCAACCTCTGCCTTCTGGGTTCAAGCGATTCTCCTGCCTTAGCCTCCCGAGTAGCTGGGATTACAGGCACCTGCCACCACGTCCGGCTAATTTTTTGTATTTTGAGTAGAGACGGGGTTTCACCATAATGGTCAGGCTGTTCTCAAACTCCTGATCTCAGGTGATCCACCCATCTCGGCCTCCCAAAGTGCTGGGATTACTGGCGTGAGCCACCGCACCCGGCCTTGATGTTTATTTTATAAAGCACTGTAATTTTGTAGCTGATGACAAAAGGCAGCCAAATGTTTTTGATAAATCAGTGGCAACTGTATTTTTGTCTTTTGAAATAACTCTGAAAACATCAGGACAACATAGATTTCAACCTGATAGCACACCACACACAGTGAGCTGTTGCTTTTTAAATTCTGAAGCCTTGTCAGGTTTGCTTCCTAGATTTCAAGTGTTTAAAATAATTCTATCTATGAAACTGAAGGATGAAGCAGATCTCTGACTGACATGTAAAAAAAAATGCCCTTTGAGGGTGTATGGTGGAGATAAATGTTTCTGAATTCAGTAAAATTGATTCCTAAGTATATTATCCTAATCCTGTTTGCTACAGTTGGTATAAAAAGGCATGAAATATGTATTCAATACCTCTTATGTAACCAAAACCATTTTTAATTAGCTTTTAAGGACTGAGAGAGCATCATGTTCAACTGGCATGCAGTCTGCCTGCATTGCCAATGAAGTCCTCAACTGTTTAATATTTTGAACTAATATTATTTATAATCTATGAATTTAATCTTTTTTGAAAGACTTTAATAATTTGAGTCTCTGAGAGGATACTTTCAATTTCCATGGGGGACTTATTTGTTGGGGATCTTAAATAAGATTCCTTTTGATCTACCGGAATATACATGTACAGAGTACATTGGATCATGTTGGAAAGAAGGCAAGTGAAAAGGTCAGAGATGAAGTAGCAAAGTTATGGAATATCGTGGAAAGGATACTAGTTGTGAAATGGAAAGAGACAAGTTATAGTACCCCAAAAGCAAAACAAGCAGGAGATGCAAGAGATGCCCCAAAAGGACAAAGCAACAATTTTCTGTTGCCACCTTTATACCGGAAGACTCTGTTGTAGAAGAAAAGAAGGCTTTGGTGCACCTTATGTGGGAGGAGGAGGGGCAGGGCATGCTGATGCTGAGCGTACAGGCAGACAAGAGCGTAGCCTGCTGTTGCCTCCATCACTATGAAATGACTTATTTTACCTGAAGGACCCATGGTTTATGTTCCTCTAATTCCTTTCACTCTCCCTAAGCCCTCTGAGAGAGATGAAGATAGATGATTTTATTGCTACTAAATTGAAGGGAGCACTATTTCTTTTTGTCTTTTGTTAGCAAAAAATTGCAAAAAGAATTGTACATTCTTGCTAAAAATAAATAAATAAATAAAAAATTAAAAAAACAAGGGACCTAACAAAACTCAGCAGTGTTACTGTATTTTTAAAAAATATTTTTATAGACTCATTTTCAGGTTATTAAATGTAAGAGAAACAGATACCCCTCTTTTTTAAAGTAGGTAAATCATTGATGATTTATATTACCAATTTTTAGAAGTAATTTTCTAGTAAGCTTGTGGCATCAGAAAATACTAGAAGATTTTTTTAGTTAAATTAGTTAGAACATTTATGAATGAATATAATAAATATTTTTTCAGAATAAAATATGGACCCTTTGTGTTTACTAATAGATAAAGCCAGATATAATTTTTTGTTTTTAAGGCCACAAAATATGGCCTTTGTTAAAGAACACTAAAGTTAGAAATCTAAAGTTAGAGCAACTTTTTAATGGCTATTTCCTATTATTGTAAGTGTTAAAACCCCTGCAGAATTCTTGATAAGGTGCTATTTATACTATATTTCTTATTATAAGATAACTGTCTTTAGTCTTCTTAGTACTAGTCTTTTTAGTACTAAATCAATCAGTAAACATCATCATTTCACCCCAAAATTTTGTCACAGAAAAGGCGTATCAAATGAAAAATAATTTCAGAGATCTTTCTTTCAAGATATTTTTTCCTGATAAAATACATTGTCTTGAAGTAAATACATTGTCAAAACCTAATTGCAATTCTGTTAAATCTAAGTAATTTTTAGACAGTGTTTCACCGTATTATTTAGGATGTGAAATGCCATTTCTTTCACTGATTACACCATATACAGGAAACAGGTAAAACAGTGAAAACTTTATTGTGCTGGTTGATGCCAACTTGGTTGAAAAGCTCTCTGCAGAAGAAGTGATCTAGACTGACAGAAGTGTTGCTAATTACAAGTTGTGTTCTCATGACGTAATTAGAAAGTAACTTCTCAAAGTACAACTTTTATGAAAAAAATAAGCTGTTAAAAAAAGGAAATCGTAGGTTAATTTAATTGGGAAAATGGGCAATTGACAGAGACCATTTTCCTAACACATATATGTGCTAGTACTTTAACTTTTTAAAATTTTACTTCTACGTTTTGTAATATAAAAATTTCTATTTTAAGTTTAGAATGTTATACGTACCGAAAGTATGCAGCCAAATCGATCAGATCAAACCATTTTACCTGGAGTTTGGTACTGGTTTTTACTTCTCTGAATCTGTATAAGAAAAATAAAGACAATTGAACTTCCA";
        String actual = predictor.getAlternateCdnaSequence();
        Assert.assertEquals(expected, actual);

        Assert.assertEquals("LEU", predictor.buildingComponents.getAlternate());


        Assert.assertEquals("ENSP00000419465:p.Leu400fs", predictor.calculate());
    }





    private Transcript getTranscript(Gene gene, String id) {
        for (Transcript transcript : gene.getTranscripts()) {
            if (transcript.getId().equals(id)) {
                return transcript;
            }
        }
        return null;
    }

    private Gene getGene(String id) {
        for (Gene gene : geneList) {
            if (gene.getId().equals(id)) {
                return gene;
            }
        }
        return null;
    }

    private List<Gene> loadGenes(Path path) throws IOException {
        List<Gene> repeatSet = new ArrayList<>();

        try (BufferedReader bufferedReader = FileUtils.newBufferedReader(path)) {
            String line = bufferedReader.readLine();
            while (line != null) {
                repeatSet.add(jsonObjectMapper.convertValue(JSON.parse(line), Gene.class));
                line = bufferedReader.readLine();
            }
        }

        return repeatSet;
    }
}