
db.getCollection('core').ensureIndex({'id': 1})
db.getCollection('core').ensureIndex({'name': 1})
db.getCollection('core').ensureIndex({'biotype': 1})
db.getCollection('core').ensureIndex({'chunkIds': 1})
db.getCollection('core').ensureIndex({'chromosome': 1, "start": 1, "end": 1})
db.getCollection('core').ensureIndex({'transcripts.id': 1})
db.getCollection('core').ensureIndex({'transcripts.name': 1})
db.getCollection('core').ensureIndex({'transcripts.biotype': 1})
db.getCollection('core').ensureIndex({'transcripts.chromosome': 1})
db.getCollection('core').ensureIndex({'transcripts.xrefs.id': 1})
db.getCollection('core').ensureIndex({'transcripts.xrefs.dbName': 1})
db.getCollection('core').ensureIndex({'transcripts.xrefs.dbNameShort': 1})
db.getCollection('core').ensureIndex({'transcripts.exons.id': 1})
db.getCollection('core').ensureIndex({'transcripts.exons.chromosome': 1})