/*
 * Copyright 2015 OpenCB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencb.cellbase.core.common.regulatory;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1


/**
 * MirnaDisease generated by hbm2java.
 */
public class MirnaDisease implements java.io.Serializable {

    private int mirnaDiseaseId;
    private MirnaGene mirnaGene;
    private String mirbaseId;
    private String diseaseName;
    private String pubmedId;
    private String description;

    public MirnaDisease() {
    }

    public MirnaDisease(int mirnaDiseaseId, MirnaGene mirnaGene, String mirbaseId, String diseaseName, String pubmedId,
                        String description) {
        this.mirnaDiseaseId = mirnaDiseaseId;
        this.mirnaGene = mirnaGene;
        this.mirbaseId = mirbaseId;
        this.diseaseName = diseaseName;
        this.pubmedId = pubmedId;
        this.description = description;
    }

    public int getMirnaDiseaseId() {
        return this.mirnaDiseaseId;
    }

    public void setMirnaDiseaseId(int mirnaDiseaseId) {
        this.mirnaDiseaseId = mirnaDiseaseId;
    }

    public MirnaGene getMirnaGene() {
        return this.mirnaGene;
    }

    public void setMirnaGene(MirnaGene mirnaGene) {
        this.mirnaGene = mirnaGene;
    }

    public String getMirbaseId() {
        return this.mirbaseId;
    }

    public void setMirbaseId(String mirbaseId) {
        this.mirbaseId = mirbaseId;
    }

    public String getDiseaseName() {
        return this.diseaseName;
    }

    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

    public String getPubmedId() {
        return this.pubmedId;
    }

    public void setPubmedId(String pubmedId) {
        this.pubmedId = pubmedId;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
