package org.opencb.cellbase.core.common.regulatory;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1


/**
 * MirnaGeneToMature generated by hbm2java
 */
public class MirnaGeneToMature implements java.io.Serializable {

	private int mirnaGeneToMatureId;
	private MirnaGene mirnaGene;
	private MirnaMature mirnaMature;

	public MirnaGeneToMature() {
	}

	public MirnaGeneToMature(int mirnaGeneToMatureId, MirnaGene mirnaGene,
			MirnaMature mirnaMature) {
		this.mirnaGeneToMatureId = mirnaGeneToMatureId;
		this.mirnaGene = mirnaGene;
		this.mirnaMature = mirnaMature;
	}

	public int getMirnaGeneToMatureId() {
		return this.mirnaGeneToMatureId;
	}

	public void setMirnaGeneToMatureId(int mirnaGeneToMatureId) {
		this.mirnaGeneToMatureId = mirnaGeneToMatureId;
	}

	public MirnaGene getMirnaGene() {
		return this.mirnaGene;
	}

	public void setMirnaGene(MirnaGene mirnaGene) {
		this.mirnaGene = mirnaGene;
	}

	public MirnaMature getMirnaMature() {
		return this.mirnaMature;
	}

	public void setMirnaMature(MirnaMature mirnaMature) {
		this.mirnaMature = mirnaMature;
	}

}
