package org.opencb.cellbase.core.common.regulatory;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1


import org.opencb.cellbase.core.common.core.Gene;
import org.opencb.cellbase.core.common.core.Transcript;

/**
 * MirnaToGene generated by hbm2java
 */
public class MirnaToGene implements java.io.Serializable {

	private int mirnaToGeneId;
	private MirnaGene mirnaGene;
	private Transcript transcript;
	private Gene gene;

	public MirnaToGene() {
	}

	public MirnaToGene(int mirnaToGeneId, MirnaGene mirnaGene,
			Transcript transcript, Gene gene) {
		this.mirnaToGeneId = mirnaToGeneId;
		this.mirnaGene = mirnaGene;
		this.transcript = transcript;
		this.gene = gene;
	}

	public int getMirnaToGeneId() {
		return this.mirnaToGeneId;
	}

	public void setMirnaToGeneId(int mirnaToGeneId) {
		this.mirnaToGeneId = mirnaToGeneId;
	}

	public MirnaGene getMirnaGene() {
		return this.mirnaGene;
	}

	public void setMirnaGene(MirnaGene mirnaGene) {
		this.mirnaGene = mirnaGene;
	}

	public Transcript getTranscript() {
		return this.transcript;
	}

	public void setTranscript(Transcript transcript) {
		this.transcript = transcript;
	}

	public Gene getGene() {
		return this.gene;
	}

	public void setGene(Gene gene) {
		this.gene = gene;
	}

}
