/*
 * Copyright 2015 OpenCB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencb.cellbase.core.common.regulatory;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1


/**
 * MirnaGeneToMature generated by hbm2java.
 */
public class MirnaGeneToMature implements java.io.Serializable {

    private int mirnaGeneToMatureId;
    private MirnaGene mirnaGene;
    private MirnaMature mirnaMature;

    public MirnaGeneToMature() {
    }

    public MirnaGeneToMature(int mirnaGeneToMatureId, MirnaGene mirnaGene, MirnaMature mirnaMature) {
        this.mirnaGeneToMatureId = mirnaGeneToMatureId;
        this.mirnaGene = mirnaGene;
        this.mirnaMature = mirnaMature;
    }

    public int getMirnaGeneToMatureId() {
        return this.mirnaGeneToMatureId;
    }

    public void setMirnaGeneToMatureId(int mirnaGeneToMatureId) {
        this.mirnaGeneToMatureId = mirnaGeneToMatureId;
    }

    public MirnaGene getMirnaGene() {
        return this.mirnaGene;
    }

    public void setMirnaGene(MirnaGene mirnaGene) {
        this.mirnaGene = mirnaGene;
    }

    public MirnaMature getMirnaMature() {
        return this.mirnaMature;
    }

    public void setMirnaMature(MirnaMature mirnaMature) {
        this.mirnaMature = mirnaMature;
    }

}
