
version: "${CELLBASE.VERSION}"
apiVersion: "${project.version}"
wiki: https://github.com/opencb/cellbase/wiki
maintenanceFlagFile: "/tmp/maintenance"
maintainerContact: ignacio.medina@zettagenomics.com
logLevel: "INFO"
logDir: "./logs"
# where to output the logs
# can be "console" or "file", defaults to console
logOutput: "file"
# For testing
secretKey: "xPacig89igHSieEnveJEi4KCfdEslhmssC3vui1JJQGgDQ0y8v"
databases:
  mongodb:
    host: "${CELLBASE.DB.MONGODB.HOST}"
    user: "${CELLBASE.DB.USER}"
    password: "${CELLBASE.DB.PASSWORD}"
    shards:
      - id: "${CELLBASE.DB.MONGODB.REPLICASET.0.NAME}"
        nodes: "${CELLBASE.DB.MONGODB.REPLICASET.0}"
      - id: "${CELLBASE.DB.MONGODB.REPLICASET.1.NAME}"
        nodes: "${CELLBASE.DB.MONGODB.REPLICASET.1}"
    options:
      authenticationDatabase: "${CELLBASE.DB.MONGODB.AUTHENTICATIONDATABASE}"
      authenticationMechanism: "${CELLBASE.DB.MONGODB.AUTHENTICATION_MECHANISM}"
      readPreference: "${CELLBASE.DB.MONGODB.READPREFERENCE}"
      replicaSet: "${CELLBASE.DB.MONGODB.REPLICASET}"
      connectionsPerHost: 20
      sslEnabled: false
#      sslInvalidCertificatesAllowed: true
#      sslInvalidHostnameAllowed: true
      enableSharding: false
  neo4j:
    hsapiens:
      host: "${CELLBASE.DB.NEO4J.HOST}"
      user: "${CELLBASE.DB.USER}"
      password: "${CELLBASE.DB.PASSWORD}"
    mmusculus:
      host: "${CELLBASE.DB.NEO4J.HOST}"
      user: "${CELLBASE.DB.USER}"
      password: "${CELLBASE.DB.PASSWORD}"
server:
  rest:
    port: "${CELLBASE.SERVER.REST.PORT}"
defaultOutdir: "/tmp"
download:
  ensembl:
    database:
      host: ensembldb.ensembl.org:3306
      user: anonymous
      password: ''
    libs: "${CELLBASE.ENSEMBL.LIBS}"
    url:
      host: ftp://ftp.ensembl.org/pub
  ensemblGenomes:
    database:
      host: mysql-eg-publicsql.ebi.ac.uk:4157
      user: anonymous
      password: ''
    libs: "${CELLBASE.ENSEMBL.LIBS}"
    url:
      host: ftp://ftp.ensemblgenomes.org/pub
  hgnc:
    host: https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/monthly/tsv/hgnc_complete_set_2022-01-01.txt
  refSeq:
    host: https://ftp.ncbi.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.gtf.gz
  refSeqFasta:
    host: https://ftp.ncbi.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz
  refSeqProteinFasta:
    host: https://ftp.ncbi.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_protein.faa.gz
  refSeqCdna:
    host: https://ftp.ncbi.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_rna.fna.gz
  maneSelect:
#    host: https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_0.93/MANE.GRCh38.v0.93.summary.txt.gz
    host: https://ftp.ncbi.nlm.nih.gov/refseq/MANE/MANE_human/release_1.0/MANE.GRCh38.v1.0.summary.txt.gz
    version: 0.93
  lrg:
    host: http://ftp.ebi.ac.uk/pub/databases/lrgex/list_LRGs_transcripts_xrefs.txt
  geneUniprotXref:
    host: http://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/
  geneExpressionAtlas:
    host: ftp://ftp.ebi.ac.uk/pub/databases/microarray/data/gxa/allgenes_updown_in_organism_part_2.0.14.tab.gz
  mirbase:
    host: ftp://mirbase.org/pub/mirbase/CURRENT/miRNA.xls.gz
  mirbaseReadme:
    host: ftp://mirbase.org/pub/mirbase/CURRENT/README
  targetScan:
    host: http://hgdownload.cse.ucsc.edu/goldenPath/
  miRTarBase:
    host: https://mirtarbase.cuhk.edu.cn/~miRTarBase/miRTarBase_2022/cache/download/8.0/hsa_MTI.xlsx
  uniprot:
    host: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz
  uniprotRelNotes:
    host: ftp://ftp.uniprot.org/pub/databases/uniprot/relnotes.txt
  intact:
    host: ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact.txt
  interpro:
    host: ftp://ftp.ebi.ac.uk/pub/databases/interpro/current/protein2ipr.dat.gz
  interproRelNotes:
    host: ftp://ftp.ebi.ac.uk/pub/databases/interpro/current/release_notes.txt
  conservation:
    host: https://hgdownload.cse.ucsc.edu/goldenPath/
  gerp:
    host: http://ftp.ensembl.org/pub/release-104/compara/conservation_scores/90_mammals.gerp_conservation_score/gerp_conservation_scores.homo_sapiens.GRCh38.bw
  clinvar:
#    host: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_2021-07.xml.gz
#    host: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_2022-02.xml.gz
    host: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarFullRelease_2022-11.xml.gz
  clinvarVariation:
#    host: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/clinvar_variation/ClinVarVariationRelease_2021-07.xml.gz
#    host: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/clinvar_variation/ClinVarVariationRelease_2022-02.xml.gz
    host: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/clinvar_variation/ClinVarVariationRelease_2022-11.xml.gz
  clinvarSummary:
    host: http://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz
  clinvarVariationAllele:
    host: http://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variation_allele.txt.gz
  clinvarEfoTerms:
    host: ftp://ftp.ebi.ac.uk/pub/databases/eva/ClinVar/2015/ClinVar_Traits_EFO_Names_260615.csv
  iarctp53:
    host: http://p53.iarc.fr/ajax/Zipper.ashx
  docm:
    host: http://docm.info/api/
  docmVersion:
    host: http://docm.info
  dgv:
    host: http://dgv.tcag.ca/v106/docs
  simpleRepeats:
    host: http://hgdownload.cse.ucsc.edu/goldenPath
  windowMasker:
    host: http://hgdownload.cse.ucsc.edu/goldenPath
  genomicSuperDups:
    host: http://hgdownload.cse.ucsc.edu/goldenPath
  gwasCatalog:
    host: http://resources.opencb.org/opencb/cellbase/data/gwas/gwas_catalog_v1.0.2-associations_e106_r2022-05-17.tsv
    version: "1.0.2 associations_e106_r2022-05-17"
  hpo:
    host: https://ci.monarchinitiative.org/view/hpo/job/hpo.annotations/lastSuccessfulBuild/artifact/rare-diseases/util/annotation/phenotype_to_genes.txt
  disgenet:
    host: https://www.disgenet.org/static/disgenet_ap1/files/downloads
    files:
      - all_gene_disease_associations.tsv.gz
      - readme.txt
  dgidb:
    host: https://dgidb.org/data/monthly_tsvs/2021-Jan/interactions.tsv
  cadd:
    host: https://krishna.gs.washington.edu/download/CADD/v1.6/GRCh38/whole_genome_SNVs.tsv.gz
  reactome:
    host: http://www.reactome.org/download/current/biopax.zip
  gnomadConstraints:
    host: https://storage.googleapis.com/gcp-public-data--gnomad/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_transcript.txt.bgz
    version: 2.1.1
  hpoObo:
    host: http://purl.obolibrary.org/obo/hp.obo
  goObo:
    host: http://purl.obolibrary.org/obo/go/go-basic.obo
  doidObo:
    host: http://purl.obolibrary.org/obo/doid.obo
  goAnnotation:
    host: http://geneontology.org/gene-associations/goa_human.gaf.gz
  revel:
    host: https://zenodo.org/record/7072866/files/revel-v1.3_all_chromosomes.zip
  pubmed:
    host: https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/
    files:
      - pubmed22n[1..1114..4].xml.gz
  pharmGKB:
    host: https://www.pharmgkb.org/downloads
    version: v1
    files:
      - https://api.pharmgkb.org/v1/download/file/data/genes.zip
      - https://api.pharmgkb.org/v1/download/file/data/chemicals.zip
      - https://api.pharmgkb.org/v1/download/file/data/variants.zip
      - https://api.pharmgkb.org/v1/download/file/data/guidelineAnnotations.json.zip
      - https://api.pharmgkb.org/v1/download/file/data/variantAnnotations.zip
      - https://api.pharmgkb.org/v1/download/file/data/clinicalAnnotations.zip
      - https://api.pharmgkb.org/v1/download/file/data/clinicalVariants.zip
      - https://api.pharmgkb.org/v1/download/file/data/drugLabels.zip
      - https://api.pharmgkb.org/v1/download/file/data/relationships.zip
species:
  vertebrates:
    - id: hsapiens
      scientificName: Homo sapiens
      assemblies:
        - ensemblVersion: '104_38'
          name: GRCh38
        - ensemblVersion: '82_37'
          name: GRCh37
      data:
        - clinical_variants
        - conservation
        - gene
        - genome
        - missense_variation_functional_score
        - ontology
        - protein
        - refseq
        - regulation
        - repeats
        - variation_functional_score
        - splice_score
      shards:
        - collection: "variation"
          key:
            - chromosome
            - start
            - end
          rangeKey: "chromosome"
          zones:
            - name: "zone0"
              shardRanges:
                - minimum: "1"
                  maximum: "10"
                - minimum: "2"
                  maximum: "20"
                - minimum: "3"
                  maximum: "9"
            - name: "zone1"
              shardRanges:
                - minimum: "10"
                  maximum: "2"
                - minimum: "20"
                  maximum: "3"
                - minimum: "9"
                  maximum: "Z"
    - id: mmusculus
      scientificName: Mus musculus
      assemblies:
        - ensemblVersion: '82_38'
          name: GRCm38
      data:
        - genome
        - genome_info
        - gene
        - variation
        - regulation
        - protein
        - conservation
    - id: drerio
      scientificName: Danio rerio
      assemblies:
        - ensemblVersion: '82_10'
          name: GRCz10
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: rnorvegicus
      scientificName: Rattus norvegicus
      assemblies:
        - ensemblVersion: '82_6'
          name: Rnor_6.0
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: ptroglodytes
      scientificName: Pan troglodytes
      assemblies:
        - ensemblVersion: '82_214'
          name: CHIMP2.1.4
      data:
        - genome
        - genome_info
        - gene
        - variation
    - id: ggorilla
      scientificName: Gorilla gorilla
      assemblies:
        - ensemblVersion: '82_31'
          name: gorGor3.1
      data:
        - genome
        - genome_info
        - gene
    - id: csabaeus
      scientificName: Chlorocebus sabaeus
      assemblies:
        - ensemblVersion: '82_1'
          name: ChlSab1.1
      data:
        - genome
        - genome_info
        - gene
    - id: sscrofa
      scientificName: Sus scrofa
      assemblies:
        - ensemblVersion: '82_102'
          name: Sscrofa10.2
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: cfamiliaris
      scientificName: Canis familiaris
      assemblies:
        - ensemblVersion: '82_31'
          name: CanFam3.1
      data:
        - genome
        - genome_info
        - gene
        - variation
  metazoa:
    - id: celegans
      scientificName: Caenorhabditis elegans
      assemblies:
        - ensemblVersion: '29_82_245'
          name: WBcel235
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: dmelanogaster
      scientificName: Drosophila melanogaster
      assemblies:
        - ensemblVersion: '29_82_6'
          name: BDGP6
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: agambiae
      scientificName: Anopheles gambiae
      assemblies:
        - ensemblVersion: '29_82_4'
          name: AgamP4
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
  fungi:
    - id: scerevisiae
      scientificName: Saccharomyces cerevisiae
      assemblies:
        - ensemblVersion: '29_82_4'
          name: R64-1-1
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: afumigatus
      scientificName: Aspergillus fumigatus
      assemblies:
        - ensemblVersion: '29_82_2'
          name: CADRE
      data:
        - genome
        - genome_info
        - gene
    - id: anidulans
      scientificName: Aspergillus nidulans
      assemblies:
        - ensemblVersion: '29_82_6'
          name: ASM1142v1
      data:
        - genome
        - genome_info
        - gene
  protist:
    - id: pfalciparum
      scientificName: Plasmodium falciparum
      assemblies:
        - ensemblVersion: '29_82_3'
          name: ASM276v1
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: lmajor
      scientificName: Leishmania major
      assemblies:
        - ensemblVersion: '29_82_2'
          name: ASM272v2
      data:
        - genome
        - genome_info
        - gene
  plants:
    - id: athaliana
      scientificName: Arabidopsis thaliana
      assemblies:
        - ensemblVersion: '29_82_10'
          name: TAIR10
      data:
        - genome
        - genome_info
        - gene
        - variation
        - protein
    - id: osativa
      scientificName: Oryza sativa
      assemblies:
        - ensemblVersion: '29_82_7'
          name: IRGSP-1.0
      data:
        - genome
        - genome_info
        - gene
        - variation
    - id: gmax
      scientificName: Glycine max
      assemblies:
        - ensemblVersion: '29_82_1'
          name: V1.0
      data:
        - genome
        - genome_info
        - gene
    - id: vvinifera
      scientificName: Vitis vinifera
      assemblies:
        - ensemblVersion: '29_82_3'
          name: IGGP_12x
      data:
        - genome
        - genome_info
        - gene
        - variation
    - id: zmays
      scientificName: Zea mays
      assemblies:
        - ensemblVersion: '29_82_6'
          name: AGPv3
      data:
        - genome
        - genome_info
        - gene
        - variation
    - id: sbicolor
      scientificName: Sorghum bicolor
      assemblies:
        - ensemblVersion: '29_82_14'
          name: Sorbi1
      data:
        - genome
        - genome_info
        - gene
        - variation
    - id: slycopersicum
      scientificName: Solanum lycopersicum
      assemblies:
        - ensemblVersion: '29_82_250'
          name: GCA_000188115.2
      data:
        - genome
        - genome_info
        - gene
        - variation
  virus:
    - id: evirus
      scientificName: Ebola virus
      assemblies:
        - name: KM034562v1
      data:
        - genome
        - gene
  bacteria:
    - id: mpneumoniae
      scientificName: Mycoplasma pneumoniae M129
      assemblies:
        - ensemblVersion: '29_82_1'
          ensemblCollection: bacteria_0_collection
          name: ASM2734v1
      data:
        - genome
        - genome_info
        - gene
        - protein
    - id: ecoli
      scientificName: Escherichia coli
      assemblies:
        - ensemblVersion: '29_82_1'
          ensemblCollection: bacteria_91_collection
          name: HUSEC2011CHR1
      data:
        - genome
        - genome_info
        - gene
        - protein
