
db.getCollection('mutation').ensureIndex({'chunkIds': 1})
db.getCollection('mutation').ensureIndex({'id': 1})
db.getCollection('mutation').ensureIndex({'chromosome': 1, "start": 1, "end": 1})
db.getCollection('mutation').ensureIndex({'protein': 1, "proteinStart": 1})
db.getCollection('mutation').ensureIndex({'gene': 1})
db.getCollection('mutation').ensureIndex({'transcriptId': 1})
db.getCollection('mutation').ensureIndex({'sampleName': 1})
db.getCollection('mutation').ensureIndex({'primarySite': 1})
db.getCollection('mutation').ensureIndex({'siteSubtype': 1})
db.getCollection('mutation').ensureIndex({'primaryHistology': 1})
db.getCollection('mutation').ensureIndex({'histologySubtype': 1})
db.getCollection('mutation').ensureIndex({'description': 1})
