/*
 * Copyright 2015 OpenCB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opencb.cellbase.core.common.variation;

// Generated Jun 5, 2012 6:41:13 PM by Hibernate Tools 3.4.0.CR1


/**
 * MutationPhenotypeAnnotation generated by hbm2java.
 */
@Deprecated
public class MutationPhenotypeAnnotation implements java.io.Serializable {

    private int mutationPhenotypeId;
    private String chromosome;
    private int start;
    private int end;
    private String geneName;
    private String uniprotName;
    private String ensemblTranscript;
    private String primarySite;
    private String siteSubtype;
    private String primaryHistology;
    private String mutationCds;
    private String mutationAa;
    private String mutationDescription;
    private String mutationZigosity;
    private int pubmedId;
    private String description;
    private String source;

    public MutationPhenotypeAnnotation() {
    }

    public MutationPhenotypeAnnotation(int mutationPhenotypeId,
                                       String chromosome, int start, int end, String geneName,
                                       String uniprotName, String ensemblTranscript, String primarySite,
                                       String siteSubtype, String primaryHistology, String mutationCds,
                                       String mutationAa, String mutationDescription,
                                       String mutationZigosity, int pubmedId, String description,
                                       String source) {
        this.mutationPhenotypeId = mutationPhenotypeId;
        this.chromosome = chromosome;
        this.start = start;
        this.end = end;
        this.geneName = geneName;
        this.uniprotName = uniprotName;
        this.ensemblTranscript = ensemblTranscript;
        this.primarySite = primarySite;
        this.siteSubtype = siteSubtype;
        this.primaryHistology = primaryHistology;
        this.mutationCds = mutationCds;
        this.mutationAa = mutationAa;
        this.mutationDescription = mutationDescription;
        this.mutationZigosity = mutationZigosity;
        this.pubmedId = pubmedId;
        this.description = description;
        this.source = source;
    }

    public int getMutationPhenotypeId() {
        return this.mutationPhenotypeId;
    }

    public void setMutationPhenotypeId(int mutationPhenotypeId) {
        this.mutationPhenotypeId = mutationPhenotypeId;
    }

    public String getChromosome() {
        return this.chromosome;
    }

    public void setChromosome(String chromosome) {
        this.chromosome = chromosome;
    }

    public int getStart() {
        return this.start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getEnd() {
        return this.end;
    }

    public void setEnd(int end) {
        this.end = end;
    }

    public String getGeneName() {
        return this.geneName;
    }

    public void setGeneName(String geneName) {
        this.geneName = geneName;
    }

    public String getUniprotName() {
        return this.uniprotName;
    }

    public void setUniprotName(String uniprotName) {
        this.uniprotName = uniprotName;
    }

    public String getEnsemblTranscript() {
        return this.ensemblTranscript;
    }

    public void setEnsemblTranscript(String ensemblTranscript) {
        this.ensemblTranscript = ensemblTranscript;
    }

    public String getPrimarySite() {
        return this.primarySite;
    }

    public void setPrimarySite(String primarySite) {
        this.primarySite = primarySite;
    }

    public String getSiteSubtype() {
        return this.siteSubtype;
    }

    public void setSiteSubtype(String siteSubtype) {
        this.siteSubtype = siteSubtype;
    }

    public String getPrimaryHistology() {
        return this.primaryHistology;
    }

    public void setPrimaryHistology(String primaryHistology) {
        this.primaryHistology = primaryHistology;
    }

    public String getMutationCds() {
        return this.mutationCds;
    }

    public void setMutationCds(String mutationCds) {
        this.mutationCds = mutationCds;
    }

    public String getMutationAa() {
        return this.mutationAa;
    }

    public void setMutationAa(String mutationAa) {
        this.mutationAa = mutationAa;
    }

    public String getMutationDescription() {
        return this.mutationDescription;
    }

    public void setMutationDescription(String mutationDescription) {
        this.mutationDescription = mutationDescription;
    }

    public String getMutationZigosity() {
        return this.mutationZigosity;
    }

    public void setMutationZigosity(String mutationZigosity) {
        this.mutationZigosity = mutationZigosity;
    }

    public int getPubmedId() {
        return this.pubmedId;
    }

    public void setPubmedId(int pubmedId) {
        this.pubmedId = pubmedId;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

}
