---
title: "Basic usage of cellbaseR"
author: "Mohammed Omar Elsiddieg Abdallah"
date: "19 April 2016"
output: 
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Basic usage of cellbaseR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading the library

```{r, eval=FALSE }
library(cellbaseR)

```

## The CellbaseQuery class

Defining the CellbaseQuery object holding the config to connect to cellbase data

```{r , eval=TRUE}
cb <- cellbaseR::CellbaseQuery()
cb

```

making a query through cbRegion to get all the clinically relevant variants in a specific region
```{r, eval=FALSE}

res <- cellbaseR::cbRegion(object = cb,ids = "17:1000000-1100000",resource = "clinical")
# to get the data 
res <- cellbaseR::cellbaseData(res)

```
Getting annotation for a specific variant


```{r,eval=FALSE}
res2 <- cbVariant(object =cb,ids = "1:169549811:A:G",resource = "annotation")
# to get the data 
res2 <- cellbaseR::cellbaseData(res2)
```



