name: Azure tunnel

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_PASSWORD:
        required: true

jobs:
  tunnel:
    name: Create tunnel
    runs-on: ubuntu-22.04
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az aks get-credentials --resource-group opencga --name aks-uks-opencga-test-001
            kubectl -n cellbase-db port-forward services/cellbase-rs0-svc 27017:27017 &