name: CellBase Develop workflow

on:
  push:
    branches:
      - develop
      - release-*
  workflow_dispatch:

jobs:
  build:
    uses: opencb/java-common-libs/.github/workflows/build-java-app-workflow.yml@develop

  test:
    uses: opencb/cellbase/.github/workflows/test-analysis.yml@develop
    needs: build
    secrets: inherit
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      SSH_TESTING_SERVER_HOST: ${{ secrets.SSH_TESTING_SERVER_HOST}}
#      SSH_TESTING_SERVER_PORT: ${{ secrets.SSH_TESTING_SERVER_PORT}}
#      SSH_TESTING_SERVER_USER: ${{ secrets.SSH_TESTING_SERVER_USER }}
#      SSH_TESTING_SERVER_PASSWORD: ${{ secrets.SSH_TESTING_SERVER_PASSWORD }}

  deploy-maven:
    uses: opencb/java-common-libs/.github/workflows/deploy-maven-repository-workflow.yml@develop
    needs: test
    with:
      maven_opts: -Dcheckstyle.skip -DCELLBASE.WAR.NAME=cellbase
    secrets: inherit
#      MAVEN_NEXUS_USER: ${{ secrets.MAVEN_NEXUS_USER }}
#      MAVEN_NEXUS_PASSWORD: ${{ secrets.MAVEN_NEXUS_PASSWORD }}
#      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
#      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

  deploy-docker:
    uses: opencb/java-common-libs/.github/workflows/deploy-docker-hub-workflow.yml@develop
    needs: test
    with:
      cli: python3 ./build/cloud/docker/docker-build.py push --images base
    secrets: inherit
#      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
#      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
