basename: Manual Junit test the project

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Cellbase branch to run the tests'
        default: 'develop'
        required: true
      fail-never:
        type: boolean
        description: 'The process executes all tests even if some fail.'
        default: false
        required: false

jobs:
  test:
    name: JUnit Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: '0'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: K8s Tunnel MongoDB
        run: |
          wget https://dl.k8s.io/release/v1.28.2/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          echo "${{ secrets.AZURE_KUBE_CONFIG }}" > admin.conf 
          ./kubectl -n cellbase-db port-forward services/cellbase-rs0-svc 27017:27017 --kubeconfig ./admin.conf &
      - name: Install dependencies branches
        run: |
          if [ -f "./.github/workflows/scripts/get_same_branch.sh" ]; then
            chmod +x ./.github/workflows/scripts/get_same_branch.sh
            ./.github/workflows/scripts/get_same_branch.sh ${{ github.ref_name }}
          else
             echo "./.github/workflows/scripts/get_same_branch.sh does not exist."
          fi
      - name: Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          FAIL_NEVER=""
          if [ "${{ github.event.inputs.fail-never }}" == "true" ]; then
            FAIL_NEVER="--fail-never"
          fi
          mvn install surefire-report:report ${FAIL_NEVER} -Dcheckstyle.skip
