name: Pull request approve workflow
run-name: 'Pull request approve workflow ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} by @${{ github.actor }}'

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  test:
    uses: ./.github/workflows/test-analysis.yml
    secrets: inherit
    with:
      upload_artifact: false
      build: false