name: Pull request approve workflow
run-name: 'Pull request approve workflow ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} by @${{ github.actor }}'

on:
  pull_request_review:
    types: [ submitted ]

jobs:

  test-xetabase:
    if: github.event.review.state == 'approved'
    name: "Run all tests before merging"
    uses: opencb/java-common-libs/.github/workflows/test-xetabase-workflow.yml@develop
    with:
      branch: develop
      task: ${{ github.event.pull_request.head.ref }}
    secrets: inherit

  test-cellbase:
    uses: ./.github/workflows/test-analysis.yml
    secrets: inherit
    with:
      upload_artifact: false
      build: false